timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile1.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile2.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile3.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile4.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile5.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile6.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile7.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile8.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile9.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile10.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile11.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile12.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile13.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile14.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile15.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile16.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile17.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile18.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile19.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/gripper pfile20.pddl
