timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p01.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p02.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p03.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p04.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p05.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p06.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p07.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p08.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p09.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p10.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p11.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p12.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p13.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p14.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p15.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p16.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p17.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p18.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p19.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p20.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p21.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p22.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p23.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p24.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p25.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p26.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p27.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p28.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p29.pddl
timeout 1200 ./r.execute /home/matheus/mestrado/comp/tpp p30.pddl
