#!/local/bin/tclsh

exec  r.execute examples/log/typed \
probLOGISTICS-10-0.pddl \
probLOGISTICS-10-1.pddl \
probLOGISTICS-11-0.pddl \
probLOGISTICS-11-1.pddl \
probLOGISTICS-12-0.pddl \
probLOGISTICS-12-1.pddl \
probLOGISTICS-13-0.pddl \
probLOGISTICS-13-1.pddl \
probLOGISTICS-14-0.pddl \
probLOGISTICS-14-1.pddl \
probLOGISTICS-15-0.pddl \
probLOGISTICS-15-1.pddl \
probLOGISTICS-4-0.pddl \
probLOGISTICS-4-1.pddl \
probLOGISTICS-4-2.pddl \
probLOGISTICS-5-0.pddl \
probLOGISTICS-5-1.pddl \
probLOGISTICS-5-2.pddl \
probLOGISTICS-6-0.pddl \
probLOGISTICS-6-1.pddl \
probLOGISTICS-6-2.pddl \
probLOGISTICS-6-3.pddl \
probLOGISTICS-7-0.pddl \
probLOGISTICS-7-1.pddl \
probLOGISTICS-8-0.pddl \
probLOGISTICS-8-1.pddl \
probLOGISTICS-9-0.pddl \
probLOGISTICS-9-1.pddl > log.result1

