/* A goal regression planner for STRIPS domain. Is has two versions:
solvep1() choose a subgoal, and commit to solving it before it moves
on to other subgoals (this is the version used in AIPS-2000 planning
competition); solvep2() computes the first actions of all the
subgoals and choose one to execute among them (this is the version that
was attempted first in planner.pl).

This planner does not rely on precomputed rules in the forms of do() and
do1() generated by solve1(N), so fluent_name(), domain(), fluent_name1()
are not needed in domain specification.
*/

:- style_check(-singleton).
:- style_check(-discontiguous).


/* logical operators: - (not), & (and), \/ (or), -> (implies), <-> (iff) */

:- op(500,fx,-).
:- op(780,xfy,&).
:- op(790,xfy,\/).
:- op(800,xfy,->).
:- op(800,xfy,<->).

/* various dynamic predicates */

:- dynamic(poss/3).
:- dynamic(effect/5).

/* forward chaining planner and post-processor */

:- dynamic initial_state/1.
:- dynamic state/2.  %state(P,S) if S is the state of do(P,S0)
:- multifile solve_a_goal/5. %user provided control information on solve_a_goal
:- dynamic solve_a_goal/5.

/* choose which goal in a set of goals to work on */
/* a point for control information */

:- dynamic precedence1/4. %for compound goals:
                          %precedence1(G1,G2,w,p) if G1 should be before
                          %G2 under w when do(p,s0) is the initial state,
                          %where w does not mention fluents
:- multifile precedence1/4.

/* choose which simple goal in a goal to work on */
/* a point for control information */

:- dynamic precedence/3. %for simple goals:
                         %precedence(g1,g2,p) if g1 should be
                         %achieved before g2 given that do(p,s0) is the
                         %initial state, where p is in reverse order
:- multifile precedence/3.

/* unachievable goals: a point for control information */

/* static goals must be true in the initial state */

:- multifile unachievable/1.
:- dynamic  unachievable/1.


/* whether a predicate is affected by an effect axiom */	  

:- dynamic static_fluent/1.


/* a new forward chaining planner by focusing on a goal, and try solve the
   goal before moving to anything else */
/* March 2000 */
/* 1. loop control by loop(_,_): will get much better plans but slower;
   2. if loop control is on, then turn on backtracking on choose_a_goal
      in find_plan1(G,P,Stack,P1); otherwise, turn it off. If there the
      loop control is off, then turn off backtracking will not lose any
      solution when the following is true: a compound goal is achievable
      iff each simple goal in it is achievable.
   3. goal ordering by order_goal(L1,L2,P): order compound goals (lists of
      simple goals) in L1 according to the number of simple goals in them
      that are already true in do(P,S0): work faster on many, but slower on
      some.
*/

/* K=0: no loop detecting, full backtracking, and deterministic
   K=1: no loop detecting, no backtracking, and deterministic
   K=2: loop detecting, full backtracking, and deterministic
   K=3: no loop detecting, no backtracking, and randomized
*/

/* K=0 and K=2 are so sloww, they are not really worth it */
/* for K=1 and K=3, the planner is complete if for any goal G, if
   it is achievable in S, then for any g in G, and any plan P for g, G is
   still achievable in do(P,S).
*/

/* deterministic versions may run into infinite cycle, see
   cycle.pl for an example. Solved by the new version now 20-4-2000 */

/* in this planner, a plan is a list in reverse order: the first action
   is the last element: to change it into the regular order, changes clauses
   marked by "reverse"  */

find_plan1(G,P,K) :-
	find_plan1(G,P1,[],[],1,K), %K is the maximum length of P1 or K=0
	post_process(P1,P2),
	reverse(P2,P).

/* post_process: get rid off pairs of complementary actions */

post_process(P,P1) :- 
	post_process1(P,P2), 
	((P=P2, P1=P);
	 post_process(P2,P1)),
	!.

post_process1([],[]).
post_process1([A],[A]).
post_process1([A2,A1|P],P1) :-   complement_action(A1,A2), 
	!, post_process1(P,P1).
post_process1([A1,A2|P],[A1|P1]) :-  
	post_process1([A2|P],P1).

/* find_plan1(G,P,Stack,P0,K,Max): find a plan P of G starting in do(P0,S0),
   where Stack is the current stack of goals, K is the control number, and Max
   is the maximum length of plan allowed */

find_plan1(G,P,_,P,K,Max) :-    
	holds_plan(G,P), 
	!.
find_plan1(G,P,Stack,P1,K,Max) :- %Max is the maximum length of P allowed
	(G=[SimpleG];
	 choose_a_goal(G,P1,SimpleG,K)),
	 (K=0;
	  K=2; 
	  ((K=1;K=3), !)), % allow backtracking when loop control is on
	find_plan_sg1(SimpleG,G,P2,[SimpleG|Stack],P1,K,Max),
	(Max=0; (length(P2,LP), LP =< Max)),
	(((K=0; K=1; K=2),
	  delete(G,SimpleG,G1),   /* for deterministic version:
                             when a simple goal is achieved, move
                             it to the end of the queue in case
			     it is made false again and needs to
			     be re-achieved */
	  append(G1,[SimpleG],G2),
	  find_plan1(G2,P,Stack,P2,K,Max));
	 (K=3,
	  find_plan1(G,P,Stack,P2,K,Max))).

							     
/* Stack is the stack of the simple goals the planner is working on */

find_plan_sg1(SimpleG,Gs,P,Stack,P1,K,Max) :-  
	solve_a_goal(SimpleG,Gs,P1,Stack,Action,Goal,K),
	((Action = nil, Goal =[],     %already true
	  P=P1);
	 (Action \== nil, Goal = [],  %made true by Action
          (K=0;  % loop detecting control
	   K=1;
	   K=3;
	   (K=2, \+ loop(P1,Action))),
	 (state([Action|P1],_);
	     (\+ state([Action|P1],_), 
	      state(P1,S1), hypo_progress(Action,S1,S2),
	      assert(state([Action|P1],S2)),
	      retractall(state(P1,_)));
	     (\+ state([Action|P1],_), 
	      \+ state(P1,_), initial_state(S),
	      strips_hypo_progress_plan([Action|P1],S,S2),
	      assert(state([Action|P1],S2)))),
	  find_plan_sg1(SimpleG,Gs,P,Stack,[Action|P1],K,Max)); /*reverse order */
	 (Goal\==[],          /* recurse to a subgoal */
          find_plan1(Goal,P3,Stack,P1,K,Max),
	  find_plan_sg1(SimpleG,Gs,P,Stack,P3,K,Max))).
%	!.   %another backtrack control point: no matter what, don't look
             %for another way to achieving a simple goal. Actually, allowing
             %backtrack here would lead to vicious cycles

/* the length of G is always > 1, and none of the goals in G are true */

choose_a_goal(G,P,NewSG,K) :-   
	(K=0;K=1;K=2),  %deterministic version
	((precedence(_,_,_),  % are there are control information?
	  first_simple_goal(G,P,NewSG));
	 (\+ precedence(_,_,_),
	   member(NewSG,G))).         

/* a randomized version. */

choose_a_goal(G,P,NewSG,K) :-   
	K=3,  %randomized version
	random_member_many(NewSG,G).

first_simple_goal(G,P,NewSG) :-
	member(NewSG1,G),
	\+ holds_plan([NewSG1],P),  
	first_simple_goal(G,NewSG1,NewSG1,NewSG,[NewSG1],P).

/* SG1 is the current goal, SG2 is the current first goal that is not
   true in do(P,S), and SG is the one to be computed */

first_simple_goal(G,SG1,SG2,SG,Stack,P) :-
	member(X,G),
	\+ member(X,Stack),
	precedence(X,SG1,P),
	((\+ holds_plan([X],P),
	  !,
	  first_simple_goal(G,X,X,SG,[X|Stack],P));
	 first_simple_goal(G,X,SG2,SG,[X|Stack],P)).
first_simple_goal(G,SG1,SG2,SG2,Stack,P).


/* try at most N times to get a random member X of Xs that has property G
If fail after N tries, then get the first X in Xs that has property G.
The whole thing fail when no X in Xs has property G */

random_member(X,Xs,G,N) :- random_member(X,Xs,G,N,1).
random_member(X,Xs,G,N,K) :- 
	K < N,
	((random_member(X,Xs),
	  G);
	 (M is K+1,
          random_member(X,Xs,G,N,M))),
	!.
random_member(X,Xs,G,N,N) :- 
	member(X,Xs),
	G.

/* random members of a list: allows backtracking until all members of the list
   have been chosen */

random_member_many(X, Xs) :-
	random_member(X1,Xs),
	(X = X1;
	 (delete(Xs,X1,Xs1), Xs1 \== [],
	 random_member_many(X,Xs1))).

/* random members of a list: allows at most N backtracking */

random_member_many(X, Xs, 1) :- !, random_member(X,Xs).
random_member_many(X, Xs, N) :- 
	random_member(X1,Xs),
	(X = X1;
	 (delete(Xs,X1,Xs1), Xs1 \== [], M is N-1,
	 random_member_many(X,Xs1,M))).


solve_a_goal(G,_,P,_,nil,[],_) :- 
	holds_plan([G],P), !.
%user wants to do it
solve_a_goal(G,Gs,P,Stack,A,Goal,K) :-  
	(K=1;K=2;K=0),     %this only makes sense for deterministic version
	solve_a_goal(G,A1,Goal1,Gs,P), %user want to do it
	!,  %don't try next one when the user want to do it
	((A=A1,Goal=Goal1);
	 (solve_a_goal(G,A2,Goal2,Gs,P),
	  \+ (A2=A1, Goal2=Goal1),
	  A=A2, Goal=Goal2)).
%check first that common goals have been achieved when there is no control
%knowledge
solve_a_goal(G,Gs,P,Stack,[],Goal,K) :- 
	(K=0;K=1;K=2),
	findall(GXV, (
	 effect(A,G,[],_,_), poss(A,XV,_),
	 static_fluent_holds(XV),
	 ground_subset(XV,GXV),
	 \+ unachievable(GXV)), LL),
	LL\==[],
	intersection(LL,Goal),
	Goal\==[],
	\+ holds_plan(Goal,P),
	!,  %if the common goals are not true yet, go achieve it, period!
	\+ (member(SG1,Goal), member(SG1,Stack)).
                    /* none of the simple goals in Goal can be in the stack */

solve_a_goal(G,Gs,P,_,A,[],K) :-  %found an action that makes G true
	(K=0;K=1;K=2),
        effect(A1,G,[],Eq,_),
	poss(A1,L,Eq1),
	holds_plan(L,P),
	static_holds(Eq), static_holds(Eq1),
	!,   %don't try next one when there is an action that can do the job
	((\+ action_loop(A1,P), 
	  \+ (member(SG,Gs), effect(A1,-SG,[],Eqs,_), static_holds(Eqs)),
	  A=A1);  %prefers the one that does not make Gs false
	 (effect(A2,G,[],Eq2,_), 
	  poss(A2,L2,Eq3),
	  holds_plan(L2,P),
	  static_holds(Eq2), static_holds(Eq3), A2\==A1,
	  \+ action_loop(A2,P), 
	  \+ (member(SG1,Gs), effect(A2,-SG1,[],Eqs1,_), static_holds(Eqs1)),
	  A=A2);
	  %otherwise, try one that will make Gs false
	 (effect(A3,G,[],Eq4,_), 
	  poss(A3,L3,Eq5),
	  holds_plan(L3,P),
	  static_holds(Eq4), static_holds(Eq5), 
	  \+ action_loop(A3,P), 
	  make_goal_false(A3,Gs),
	  A=A3)).
%	!.                 %for deterministic version, one action is enough


%if no action make the goal true, then pick an action to regress to,
%with priority given to the common goal in an action
%type first
solve_a_goal(G,Gs,P,Stack,[],Goal,K) :- 
	(K=0;K=1;K=2),
	action_name(An,_,_),
	findall(GXV, (
	 effect(A,G,[],_,_),
	 A =.. [An|_],
	 poss(A,XV,_),
	 static_fluent_holds(XV),
	 ground_subset(XV,GXV),
	 \+ unachievable(GXV)), LL),
	intersection(LL,TGoal),
	\+ (member(SG1,TGoal), member(SG1,Stack)),
	\+ unachievable(TGoal),	
	temp_pred(G,An,Stack,Goal,P,TGoal).
temp_pred(G,An,Stack,Goal,P,TGoal) :-
	\+ holds_plan(TGoal,P), !,
	  Goal=TGoal.
temp_pred(G,An,Stack,Goal,P,TGoal) :-
	effect(A0,G,[],Eq1,_), poss(A0,Goal,Eq2),
	A0 =.. [An|_],
	static_fluent_holds(Goal),
	get_ground_action(A0), /* all variables must be in A0 */
        static_holds(Eq1), static_holds(Eq2),
	\+ unachievable(Goal),
	\+ (member(SG11,Goal), member(SG11,Stack)).
	 
%for randomized version
solve_a_goal(G,Gs,P,_,A,[],K) :-  %found an action that makes G true
	K=3,
	findall(X, 
	  (effect(X,G,[],W,_), poss(X,L,W1),
	  holds_plan(L,P),     /* normal holds in a state */
          static_holds(W),  /* need more work when Eq has variables not in
                              Cond and G*/
          static_holds(W1),
	  get_ground_action(X)), LL),
	LL \== [],
	!,
	random_member_many(A,LL).

solve_a_goal(G,Gs,P,Stack,A,Goal,K) :- 
	K=3,
	findall([X,Y],
	 (effect(X,G,[],Eq1,_), poss(X,Y,Eq2),
	 get_ground_action(X), /* all variables must be in X */
         static_holds(Eq1), static_holds(Eq2),
	 \+ unachievable(Y),
	 \+ (member(SG1,Y), member(SG1,Stack))),LL),
	LL \== [],
	random_member_many([A,Goal],LL).

action_loop(A,P) :-
	append(P1,[A|P2],P), append(P3,[A|P4],P2), P1=P3.



ground_subset([],[]).
ground_subset([X|Xs],[X|Ys]) :- 
	free_variables(X,[]), 
	!,
	ground_subset(Xs,Ys).
ground_subset([X|Xs],Ys) :- 
	ground_subset(Xs,Ys).

	
intersection([],[]) :- !.
intersection([L],L) :- !.
intersection([L|LL],X) :- 
	intersection(LL,X1),
	intersection(L,X1,X).




generate_static_fluent :- 
	retractall(static_fluent(_)),
	findall(X,
	  (fluent_name(X,_,_),
	   \+ affected(X)), L),
	findall(X, (member(X,L), assert(static_fluent(X))),_).

affected(F) :- 
	effect(_, E, _, _, _),
	((E = -(E1), E1 =.. [F|_]);
	  E =.. [F|_]),
	!.

unaffacted(P) :- ((P = -P1, P1 =.. [F|_]); P =.. [F|_]), static_fluent(F).

static_fluent_holds([]).
static_fluent_holds([SG|Goal]) :- SG = eq(X,Y), !, X=Y,
  static_fluent_holds(Goal).
static_fluent_holds([SG|Goal]) :- SG = -eq(X,Y), !, 
  X \== Y,
  static_fluent_holds(Goal).
static_fluent_holds([SG|Goal]) :- unaffacted(SG), !,
  initial_state(S), member(SG,S), static_fluent_holds(Goal).
static_fluent_holds([SG|Goal]) :- static_fluent_holds(Goal).


/* loop control: check that the new action does not undo the one 
   immediately before */

loop([Action1|_],Action) :- 
  complement_action(Action1,Action).   %P (1st argument) is in reverse order



/* complement actions: when one adds what the other deletes, and vise versa,
   futhermore, the poss list of A1 must include the add list of A2, so that
   if A1 is followed immediately by A2, then this pair of actions can be
   removed */
/* work only on context free actions */

complement_action(A1,A2) :-  
	findall(X,
	  (effect(A1, -X, [], Eq,_), 
	   static_holds(Eq)), Neg1),
	findall(X,
	  (effect(A1, X, [], Eq,_), 
	   \+ X = -(_),
	   static_holds(Eq)), Pos1),
	findall(X,
	  (effect(A2, -X, [], Eq,_), 
	   static_holds(Eq)), Neg2),
	findall(X,
	  (effect(A2, X, [], Eq,_), 
	   \+ X = -(_),
	   static_holds(Eq)), Pos2),
	sort(Neg1,Neg),
	sort(Pos2,Neg),
	sort(Pos1,Pos),
	sort(Neg2,Pos),
	poss(A1,L,_),
	subset(Pos2,L).

/* achievable goals must satisfy state constraints */

%unachievable(G) :- \+ ground_goal_complete(G,_).

/* generate internal causal rules from user supplied ones */

:- dynamic rule/2.  %rule(C,Conseq): C is a list and Conseq is a static prop
:- multifile rule/2. 

generate_causal_rules :- 
	findall(_,
	 (rule(Cond,Conseq),
	  complex_instance(Cond,Cond1),
	  assert(causal_rule(Cond1,Conseq))), _).
complex_instance([],[]).
complex_instance([-F|L], NewL) :- 
	F =.. [Fn|_],
	((complex_predicates(Fn,F1,_),
	  subst_functor([-F|L],Fn,F1,L1),
	  complex_instance(L1,NewL));
	 (\+ complex_predicates(Fn,_,_),
	  complex_instance(L,L2),
	  NewL = [-F|L2])).
complex_instance([F|L], NewL) :- \+ (F = -_),
	F =.. [Fn|_],
	((complex_predicates(Fn,F1,_),
	  subst_functor([F|L],Fn,F1,L1),
	  complex_instance(L1,NewL));
	 (\+ complex_predicates(Fn,_,_),
	  complex_instance(L,L2),
	  NewL = [F|L2])).

/* replace a predicate name in a list of literals by a new one */

subst_functor([],_,_,[]).
subst_functor([F|L],Fn1,Fn2,NewL) :-
	subst_functor(L,Fn1,Fn2,L1),
	((F = -F1,
	 F1 =.. [Fn|Args],
	 ((Fn = Fn1,
	   F2 =.. [Fn2|Args],
	   NewL = [-F2|L1]);
	  (Fn \== Fn1,
	   NewL = [F|L1])));
	 (\+ (F = -_),
	  F =.. [Fn|Args],
	  ((Fn = Fn1,
	    F2 =.. [Fn2|Args],
	    NewL = [F2|L1]);
	   (Fn \== Fn1,
	    NewL = [F|L1])))).

/********** the above find_plan1() find a plan by solving one goal at a time
******/

/**** the following one pools the first actions of all subgoals and decide what
to do based on that ********/

find_plan2(G,P,K) :-
	find_plan2(G,P1,[],K,500), %500 is the maximum length of P1, not used
	post_process(P1,P2),
	reverse(P2,P).

find_plan2(G,P,P,_,_) :- holds_plan(G,P), !.
find_plan2(G,P,P1,K,_) :-
	findall(A,
	  (member(SG,G),
	   first_action(SG,G,[SG],P1,A,K),
	   A \== nil, \+ loop(P1,A),
	   \+ action_loop(A,P1)), AL), 
	AL\==[],
	sort(AL,AL1),
	(AL1=[Action];
	 (findall([N,A], (member(A,AL1),
	                  heuristic(A,AL1,AL,G,N)),
		  NAL),
	  sort(NAL,NAL1),
	  member([_,Action],NAL1))),
	 (state([Action|P1],_);
	     (\+ state([Action|P1],_), 
	      state(P1,S1), hypo_progress(Action,S1,S2),
	      assert(state([Action|P1],S2)),
	      retractall(state(P1,_)));
	     (\+ state([Action|P1],_), 
	      \+ state(P1,_), initial_state(S), 
	      strips_hypo_progress_plan([Action|P1],S,S2),
	      assert(state([Action|P1],S2)))),
	find_plan2(G,P,[Action|P1],K,_).

/* get a first action A that would lead to SimpleG in do(P1,s0), given
   that Stack is current set of simple goals that the planner has been
   trying to get a first action */

first_action(SimpleG,Gs,Stack,P1,A,K) :-
	solve_a_goal(SimpleG,Gs,P1,Stack,Action,Goal,K),
	((Action = nil, Goal =[],     %already true
	  A=Action);
	 (Goal=[],Action \== nil,  %made true by Action
          (K=0;  % loop detecting control
	   K=1;
	   K=3;
	   (K=2, \+ loop(P1,Action))),
	  A=Action);
	 (Goal\==[],          /* recurse to a subgoal */
          member(NewSG,Goal),
	  \+ holds_plan([NewSG],P1),
	  first_action(NewSG,Goal,[NewSG|Stack],P1,A,K))),
	!.  

/* how good an action A is compared to the actions in AL for achieving G, 
   and AL1 is AL with duplicates removed */

heuristic(A,AL1,AL,G,N) :-
	findall(X, member(A,AL), L1),
	length(L1,N1),  %the number of A's in AL
	findall(X, (member(X,G), 
	            effect(A,-X,[],Eq,_), static_holds(Eq)), L2),
	length(L2,N2),  %the number of goals in G made false by A
	findall(X, (member(X,G), 
	            effect(A,X,[],Eq,_), static_holds(Eq)), L3),
	length(L3,N3),  %the number of goals in G made true by A
	findall(X, (member(X,AL1), X\==A, poss(X,Poss,_),
	            make_goal_false(A,Poss)), L4),
	length(L4,N4),  %the number of actions in AL1 made not executable by A
	N is (N2+N4)/(N1+(N1*N3)).

make_goal_false(A,Poss) :- member(X,Poss), effect(A,-X,[],Eq,_),
	static_holds(Eq), !.


/*** end of the new find_plan ****/

cleanup_forward :- 
    retractall(initial_state(_)),
    retractall(static_fluent(_)),
	retractall(user_solve_a_goal(_,_)),
	retractall(found_an_action(_,_)),
	retractall(state(_,_)),
    retractall(regress(_,_,_,_,_)).

initialize :- 
	generate_static_fluent,
	findall(X, initial(X), S0),
	assert(state([],S0)),
	assert(initial_state(S0)).


holds([],_).
holds([-G|GL],S) :- \+ member(G,S), holds(GL,S).
holds([G|GL],S) :- member(G,S), holds(GL,S).


holds(G,P,S) :- 
	hypo_progress_plan(P,S,NewS),
	holds(G,NewS).

/* holds_plan(G,P) if holds(G,do(P,S0)) - used state(P,S) if it exists;
   otherwise, create state(P,S) */

holds_plan(G,P) :- state(P,S), !, holds(G,S).
holds_plan(G,P) :- initial_state(S), strips_hypo_progress_plan(P,S,S1),
	assert(state(P,S1)), !, holds(G,S1).

/* here is a version of holds1(G,P,S) for context-free actions. We assume 
   here that G is a ground goal (a list of atoms), S is a state (a set of
   atoms), and P a ground plan in reverse order, i.e. the first element
   in P is the last action 
*/

holds1(G,[],S) :- subset(G,S), !.
holds1([],_,_) :- !.
holds1([SG|G],P,S) :- holds1_sg(SG,P,S), !, 
	holds1(G,P,S).

holds1_sg(-SG,P,S) :- !, \+ holds1_sg(SG,P,S).
holds1_sg(SG,[],S) :- member(SG,S).
holds1_sg(SG,[A|P],S) :- 
	effect(A,SG,[],Eq,_),
	static_holds(Eq),
	!.
holds1_sg(SG,[A|P],S) :- 
	\+ (effect(A, -(SG), [],Eq,_), static_holds(Eq)),
	holds1_sg(SG,P,S).

/* holds2(G,P,S): like holds1, but for G that may contain variables */

holds2([],_,_) :- !.
holds2(G,[],S) :- !, holds(G,S).
holds2([SG],P,S) :- !, holds2_sg(SG,P,S).
holds2(G,P,S) :- 
	choose_one_sg_holds2(G,SG),
	((free_variables(SG,[]), !,holds1_sg(SG,P,S));
	  holds2_sg(SG,P,S)),
	delete(G,SG,G1),
	holds2(G1,P,S).
choose_one_sg_holds2(G,SG) :- 
	findall([N,X], (member(X,G),
	                 free_variables(X,L),
			 length(L,N)), LL),
	sort(LL,LL1),
	member([_,SG],LL1),
	!.

holds2_1([],_,_) :- !.
holds2_1([SG|G],P,S) :-  free_variables(SG,[]), !,
	holds1_sg(SG,P,S), holds2_1(G,P,S).
holds2_1([SG|G],P,S) :-  holds2_sg(SG,P,S), holds2_1(G,P,S).

holds2_sg(SG,[],S) :- member(SG,S).
holds2_sg(SG,[A|P],S) :- 
	effect(A,SG,[],Eq,_),
	static_holds(Eq).
holds2_sg(SG,[A|P],S) :- 
	findall(SG, holds2_sg(SG,P,S), L),
	member(SG,L),
	\+ (effect(A, -(SG), [],Eq,_), static_holds(Eq)).

    
hypo_progress(A,S,NewS) :- 
	findall(X, (effect(A, -X, C,Eq,_),
	            holds(C,S),
		    static_holds(Eq)), Neg),
	findall(X, (effect(A, X, C,Eq,_), \+ (X = -_),
	            holds(C,S),
		    static_holds(Eq)), Pos),
	subtract(S,Neg,S1),
	union(S1,Pos,NewS).
%    sort(NewS0,NewS).
		   
/* progressing a plan for STRIPS actions: the plan P is assumed to be in
   reverse order, and ground */

strips_hypo_progress_plan(P,S,NewS) :-
	add_delete_list(P,Pos,Neg),
	subtract(S,Neg,S1),
	union(S1,Pos,NewS).

add_delete_list(P,Pos,Neg) :- 
	add_delete_list(P,Pos,Neg,[],[]).

/* given that Pos1 is the list that has to be added, and Neg1 is the list that
   has to be deleted, Pos is the add list after P, and Neg is the delete
   list after P */

add_delete_list([A|P],Pos,Neg,Pos1,Neg1) :-
	findall(X, (effect(A, -X, C,Eq,_),
	            holds(C,S),
		    static_holds(Eq)), Neg0),
	findall(X, (effect(A, X, C,Eq,_), \+ (X = -_),
	            holds(C,S),
		    static_holds(Eq)), Pos0),
	subtract(Neg0,Pos1,Neg2),
	subtract(Pos0,Neg1,Pos2),
	union(Neg1,Neg2,Neg3),
	union(Pos1,Pos2,Pos3),
	add_delete_list(P,Pos,Neg,Pos3,Neg3).
add_delete_list([],Pos1,Neg1,Pos1,Neg1).
	

/* hypo_progress_plan(P,S,S1): P is in the normal order! */

hypo_progress_plan([],S,S).
hypo_progress_plan([A|As],S,NewS) :- 
    hypo_progress(A,S,NewS1), hypo_progress_plan(As,NewS1,NewS).
    

/* get_ground_action(A): instantiate the variables in A: no heuristics */

get_ground_action(A) :- free_variables(A,[]), !.
get_ground_action(ach(F)) :- 
    F =.. [Fn|Args], 
    fluent_name(Fn,_,T),
    type_match(Args,T).
get_ground_action(A) :- 
    A =.. [An|Args], 
    action_name(An,_,T),
    type_match(Args,T).
    
type_match([],[]).
type_match([Arg|Args],[T|Ts]) :-
    pdomain(T,D), member(Arg,D),
    type_match(Args,Ts).


/* check a plan */


check_it(P,G) :- 
	initial_state(S),
	check_it(P,G,S).
check_it([],G,S) :- subset(G,S).
check_it([A|P],G,S) :-
	poss(A,L,W),
	subset(L,S),
	static_holds(W),
	hypo_progress(A,S,S1),
	check_it(P,G,S1).

/* static_holds */
/* does not work when the list has variables */

static_holds([]).
static_holds([eq(X,Y)|L]) :- !, X=Y, static_holds(L).
static_holds([-eq(X,Y)|L]) :- !, X\==Y, static_holds(L).
static_holds([-P|L]) :- !, \+ P, static_holds(L).
static_holds([P|L]) :- P, !, static_holds(L).

/* instantiate variables in VarL by unique constants beginning with v_ */

make_ground_variable([]) :- !.
make_ground_variable([X|VarL]) :- free_variables(X,[_]),!,
    atom_to_term(Y,X,_), concat(v,Y,Z), X=Z,
    make_ground_variable(VarL).
make_ground_variable([X|VarL]) :- make_ground_variable(VarL).

/* variablize(G,VarL,G1)
 replace the constants in a goal by variables in VarL: function and
 predicate names cannot occurr in VarL */

variablize(G,VarL,NewG) :- term_to_atom(G,A),
  string_to_list(A,L),
  list_variablize(L,VarL,L1),
  string_to_list(S,L1),
  string_to_atom(S,A1), atom_to_term(A1,NewG,_).

/* list_variablize(L1,varL,L2): replace each constant in L1 (a list of
  characters and VarL by a
  upper case string, with L2 the resulting new list of characters */

list_variablize(L,[],L).
list_variablize(L,[V|VarL],NewL) :- term_to_atom(V,X1),
  string_concat('X',X1,X2), string_to_list(X2,L1),
  string_to_list(X1,L2),
  list_subst(L3, L2, L, L1),
  list_variablize(L3,VarL,NewL).

/* list_subst(NewL,L1,L,L2) */

list_subst([],L1,[],L2) :-  !.
list_subst(NewL,L1,L,L2) :- append(L1,L11,L), !, list_subst(L12,L1,L11,L2),
  append(L2,L12,NewL).
list_subst([C|NewL],L1,[C|L],L2) :- list_subst(NewL,L1,L,L2).


random_member(X,Xs):-
  length(Xs,L), % computes length of the list
  random(1,L,RanPos), % returns a random integer
  nth_member(X,Xs,RanPos). % picks random element X

nth_member(X,Xs,N):-member_i(X,Xs,1,N).

member_i(X,[X|_],N,N).
member_i(X,[_|Xs],N1,N3):-  
  N2 is N1+1,  
  member_i(X,Xs,N2,N3).

delete_nth_member(Xs,N,Xs1) :- 
  append(Xs11,Xs12,Xs), M is N-1,
  length(Xs11,M), Xs12=[_|Xs13],
  append(Xs11,Xs13,Xs1).


/****** Solving a problem given by a pddl file *************/

:- dynamic pdomain/2.

/* solvep(File_Name,K) for AIPS-2000. It writes the results to the
   file "result"
   It assumes that the file has exactly one problem */

:- dynamic problem_need_to_be_processed/0.
:- multifile problem_need_to_be_processed/0.

solvep(File_Name,K) :- 
	statistics(cputime,Time1),
    load_files([domainout], [silent(true)]),
    retractall(pdomain(_,_)),
    retractall(initial(_)),
    retractall(problem(_,_,_,_,_)),
    get_all_problem(File_Name),
    problem(PName,_,Domains9,Init9,Goal9),
    ((problem_need_to_be_processed, 
      preprocess_problem(Domains9,Init9,Goal9,Domains,Init2,Goal1));
     (\+ problem_need_to_be_processed, 
      Domains = Domains9, Init2 = Init9, Goal1 = Goal9)),
    complex_predicate_transform(Init2,Init,Domains),
    complex_predicate_transform(Goal1,Goal,Domains),
	length(Goal,N11),
	new_solvep(Domains,Init,Goal,P,K,N11),
	complex_plan_convert(P,P1),
	length(P1,N),
	statistics(cputime,Time2), Time is Time2-Time1,
	write(PName), write(','),
	write(Time),  write(','),
	write(N),  
	aips_out_plan(P1),
	nl.
new_solvep(Domains,Init,Goal,P,K,0) :- fail.
new_solvep(Domains,Init,Goal,P,K,N) :-
	(
	solvep(Domains,Init,Goal,P,K);
	(M is N-1, 
	 Goal = [SG|Goal1],
	 Goal1\==[],
	 append(Goal1,[SG],Goal2),
	 retractall(pdomain(_,_)),
	 retractall(initial(_)),
	 new_solvep(Domains,Init,Goal2,P,K,M))),
	!.

/* [a(1,2,3),b(t,y,u)] => (a 1 2 3),(b t y u) */

aips_out_plan([]).
aips_out_plan([A|P]) :- aips_out_action(A),
	aips_out_plan(P).

aips_out_action(A) :- write(','),
	write('('),
	A =.. AL,
	aips_out_list(AL),
	write(')').

aips_out_list([X]) :-  write(X), !.
aips_out_list([X|Xs]) :- write(X), write( ' '),
	aips_out_list(Xs).
	


solvep(PName,File_Name,DName,K) :- 
    retractall(pdomain(_,_)),
    retractall(initial(_)),
    retractall(problem(_,_,_,_,_)),
    get_all_problem(File_Name),
    problem(PName,DName,Domains9,Init9,Goal9),
    ((problem_need_to_be_processed, 
      preprocess_problem(Domains9,Init9,Goal9,Domains,Init2,Goal1));
     (\+ problem_need_to_be_processed, 
      Domains = Domains9, Init2 = Init9, Goal1 = Goal9)),
    statistics(cputime,Time1),
%    get_new_type_domain(Init1,Domains2,Init2),
%    union(Domains1,Domains2,Domains),
    complex_predicate_transform(Init2,Init,Domains),
%    sort(Init3,Init),
    complex_predicate_transform(Goal1,Goal,Domains),
%    findall(X, (member(G,Goal1),complex_predicate_convert(G,X1,Domains),
%                sort(X1,X)), XL),
%    car_product(XL,Goal),
    ((solvep(Domains,Init,Goal,P,K),
      statistics(cputime,Time2), Time is Time2-Time1,
      length(P,N),
      write(PName),nl,
      write(N),nl, write(Time),nl,
	complex_plan_convert(P,P1),
      write(P1),nl,
      retractall(initial(_)),
      retractall(pdomain(_,_)),
      fail);
     (retractall(initial(_)),
      retractall(pdomain(_,_)),
      fail)).
solvep(_,_,_,_) :- 
    retractall(problem(_,_,_,_,_)).

solvep(Domains,Init,Goal,P,K) :-    
	findall(T, (type(T,_),
		    \+ pdomain(T,_),
        	        (member([T,D],Domains);
                	 (\+ member([T,D],Domains), D=[])),
	                findall(Const, constant(Const,T), D0),
        	      	union(D,D0,D1),
			assert(pdomain(T,D1))), _),
	findall(X, (member(X,Init),assert(initial(X))),_),
	find_plan_and_check(Goal,P,K), 
	!.

:- dynamic goal_need_to_be_completed/0.
:- multifile goal_need_to_be_completed/0.

find_plan_and_check(Goal,P,K) :- 
	cleanup_forward,
	initialize,
	((goal_need_to_be_completed, complete_goal(Goal,Goal1));
	 (\+ goal_need_to_be_completed, Goal1 = Goal)),
	find_plan1(Goal1,P,K), 
%	check_it(P,Goal1), 
	!.


/* solvep2(X,K) uses new_solvep2(), solvep2(_,_,_,_) and find_plan2() */

solvep2(File_Name,K) :- 
	statistics(cputime,Time1),
    load_files([domainout], [silent(true)]),
    retractall(pdomain(_,_)),
    retractall(initial(_)),
    retractall(problem(_,_,_,_,_)),
    get_all_problem(File_Name),
    problem(PName,_,Domains9,Init9,Goal9),
    ((problem_need_to_be_processed, 
      preprocess_problem(Domains9,Init9,Goal9,Domains,Init2,Goal1));
     (\+ problem_need_to_be_processed, 
      Domains = Domains9, Init2 = Init9, Goal1 = Goal9)),
    complex_predicate_transform(Init2,Init,Domains),
    complex_predicate_transform(Goal1,Goal,Domains),
	length(Goal,N11),
	new_solvep2(Domains,Init,Goal,P,K,N11),
	complex_plan_convert(P,P1),
	length(P1,N),
	statistics(cputime,Time2), Time is Time2-Time1,
	write(PName), write(','),
	write(Time),  write(','),
	write(N),  
	aips_out_plan(P1),
	nl.
new_solvep2(Domains,Init,Goal,P,K,0) :- fail.
new_solvep2(Domains,Init,Goal,P,K,N) :-
	(
	solvep2(Domains,Init,Goal,P,K);
	(M is N-1, 
	 Goal = [SG|Goal1],
	 Goal1\==[],
	 append(Goal1,[SG],Goal2),
	 retractall(pdomain(_,_)),
	 retractall(initial(_)),
	 new_solvep2(Domains,Init,Goal2,P,K,M))),
	!.



solvep2(PName,File_Name,DName,K) :- 
    retractall(pdomain(_,_)),
    retractall(initial(_)),
    retractall(problem(_,_,_,_,_)),
    get_all_problem(File_Name),
    problem(PName,DName,Domains9,Init9,Goal9),
    ((problem_need_to_be_processed, 
      preprocess_problem(Domains9,Init9,Goal9,Domains,Init2,Goal1));
     (\+ problem_need_to_be_processed, 
      Domains = Domains9, Init2 = Init9, Goal1 = Goal9)),
    statistics(cputime,Time1),
%    get_new_type_domain(Init1,Domains2,Init2),
%    union(Domains1,Domains2,Domains),
    complex_predicate_transform(Init2,Init,Domains),
%    sort(Init3,Init),
    complex_predicate_transform(Goal1,Goal,Domains),
%    findall(X, (member(G,Goal1),complex_predicate_convert(G,X1,Domains),
%                sort(X1,X)), XL),
%    car_product(XL,Goal),
    ((solvep2(Domains,Init,Goal,P,K),
      statistics(cputime,Time2), Time is Time2-Time1,
      length(P,N),
      write(PName),nl,
      write(N),nl, write(Time),nl,
	complex_plan_convert(P,P1),
      write(P1),nl,
      retractall(initial(_)),
      retractall(pdomain(_,_)),
      fail);
     (retractall(initial(_)),
      retractall(pdomain(_,_)),
      fail)).
solvep2(_,_,_,_) :- 
    retractall(problem(_,_,_,_,_)).

solvep2(Domains,Init,Goal,P,K) :-    
	findall(T, (type(T,_),
		    \+ pdomain(T,_),
        	        (member([T,D],Domains);
                	 (\+ member([T,D],Domains), D=[])),
	                findall(Const, constant(Const,T), D0),
        	      	union(D,D0,D1),
			assert(pdomain(T,D1))), _),
	findall(X, (member(X,Init),assert(initial(X))),_),
	find_plan_and_check2(Goal,P,K), 
	!.

:- dynamic goal_need_to_be_completed/0.
:- multifile goal_need_to_be_completed/0.

find_plan_and_check2(Goal,P,K) :- 
	cleanup_forward,
	initialize,
	((goal_need_to_be_completed, complete_goal(Goal,Goal1));
	 (\+ goal_need_to_be_completed, Goal1 = Goal)),
	find_plan2(Goal1,P,K), 
%	check_it(P,Goal1), 
	!.



/* cartesian product */

car_product([],[]).
car_product([E|LL],[X|L]) :- member(X,E), car_product(LL,L).

/* find the domains of new types from the initial database, and eliminate
   those type definitions from the initial database */

:- dynamic new_domain/2.

get_new_type_domain(Init,Domains,NInit) :-
  retractall(new_domain(_,_)),
  get_new_type_domain(Init,NInit),
  findall([T,D], (new_type(T),
                  findall(X, new_domain(T,X),D)), Domains),
  retractall(new_domain(_,_)).

get_new_type_domain([],[]).
get_new_type_domain([A|Init],NInit) :-
  A =.. [F|Args],
  new_type(F), !,
  Args = [Ele], assert(new_domain(F,Ele)),
  get_new_type_domain(Init,NInit).
get_new_type_domain([A|Init],[A|NInit]) :-
  get_new_type_domain(Init,NInit).

/* convert an action back into its original form in the pddl file */

complex_action_convert(A,A1) :-
	A =.. [Ac | Args],
	complex_action(Ac1,Ac,_),
	A1 =.. [Ac1 | Args],
	!.
complex_action_convert(A,A).

/* convert a plan into its original form */

complex_plan_convert([],[]).
complex_plan_convert([A|P],[A1|P1]) :-
	complex_action_convert(A,A1), !,
	complex_plan_convert(P,P1).


/* convert a list of literals into a new list using new predicate names
*/

complex_predicate_transform([],[],_).
complex_predicate_transform([A|Init],NInit,Domains) :-
  A = -(A1), !,
  complex_predicate_convert(A1,NA,Domains),
  findall(X, (member(Y,NA), X = -(Y)), NA1),
  complex_predicate_transform(Init,NInit1,Domains),
  union(NA1,NInit1,NInit).
complex_predicate_transform([A|Init],NInit,Domains) :-
  complex_predicate_convert(A,NA,Domains),
  !,
  complex_predicate_transform(Init,NInit1,Domains),
  union(NA,NInit1,NInit).

complex_predicate_convert(A,NA,Domains) :-
  A =.. [F|Args], 
  findall(X, (find_arg_type(F,Args,Ts,Domains),
              ((complex_predicates(F,F1,Ts), X =.. [F1|Args]);
               ((\+ complex_predicates(F,_,Ts)), X=A))), NA).

/* find out the type of a tuple by looking up the domains of types, and
default to the type given by the predicate */

find_arg_type(F,Args,Ts,Domains) :-   find_arg_type(F,Args,Ts,Domains,1).
find_arg_type(_,[],[],_,_).
find_arg_type(F,[A|Args],[T|Ts],Domains,N) :-
  find_arg_type1(F,A,T,Domains,N), M is N+1,
  find_arg_type(F,Args,Ts,Domains,M).

find_arg_type1(F,A,T,Domains,_) :- 
  new_type(T), member([T,D],Domains), member(A,D).
find_arg_type1(F,A,T,Domains,N) :- 
  \+ (new_type(T1), member([T1,D],Domains), member(A,D)),
  fluent_name(F,_,Ts), !,
  nth_member(T,Ts,N).
find_arg_type1(F,A,T,Domains,_) :- 
  member([T,D],Domains), \+ type(_,T), member(A,D), !.
find_arg_type1(F,A,T,Domains,_) :- 
  member([T,D],Domains), member(A,D), !.

/**********************
pddl2forward.pl: clauses for converting pddl files to planner.pl format files
**************/


:- dynamic problem/5.

white_space(C) :- member(C, [9,10,13,32]).  % space, tab, \n, \r 
brace(C) :- member(C, [40,41]).  % ( or ) 

/* read a word from File and put it into X */

read_a_word(File,X) :- 
	get0(File,C),
        ((C = -1,X=C);
	 (white_space(C), !, read_a_word(File,X));
	 (brace(C), atom_char(X,C));
	 read_until_white_space(File,[C],X)
	 ),
         !.

/* If the next char from File is either a white-space or a brace, then
   copy Cs to X, otherwise, append the new char to Cs and continue
   recursively. read_a_word(File,X) is like read_until_white_space(File,[],X)
   except that the former will skip all the leading white-spaces */

read_until_white_space(File,Cs,X) :-
	peek_byte(File,C),
	((((white_space(C),get0(File,C));brace(C)), !,
	  string_to_list(Xs,Cs), string_to_atom(Xs,X));
	 (get0(File,C),append(Cs,[C],NewCs),
	  read_until_white_space(File,NewCs,X))),
        !.

/* read the file until either a domain description is found, or the end
   of the file is reached */

%(define (domain logistics-strips)

read_a_domain(File,Domain) :- 
  read_a_word(File,X),
  ((X = -1, Domain = -1);
   (X = '(',
    read_a_word(File,'define'),
    read_a_word(File,'('),
    read_a_word(File,'domain'),
    read_a_word(File,Domain), 
    read_a_word(File,')'))),
  !.
read_a_domain(File,Domain) :- 
  read_a_domain(File,Domain).

/* read from a file a domain description: requirements, types,
   constants, predicates, actions */

/* (define (domain logistics-strips)
   (:requirements :strips) 
   (:types t1 ... )
   (:constants a b - type, ...)
   (:predicates (OBJ ?obj)
	       	(TRUCK ?truck)
               	(LOCATION ?loc))
   (:action ...)
   ...
   (:action ...)
   ) */ 

:- dynamic domain_name/1, type/2, temp_type/1, req/1, constant/2, predicates/3, poss/1, eff/1, name/1,args/1, action/5, auto_domain/2, used_var/1, new_type/1, count/1, temp_action/5, complex_type1/2,complex_predicates/3, complex_action/3.

clean_domain :- retractall(domain_name(_)),
retractall(type(_,_)),
retractall(temp_type(_)),
retractall(req(_)),
retractall(constant(_,_)),
retractall(predicates(_,_,_)),
retractall(action(_,_,_,_,_)),
    retractall(name(_)),
    retractall(args(_)),
    retractall(poss(_)),
    retractall(eff(_)),
%retractall(count(_)),
retractall(new_type(_)),
retractall(temp_action(_,_,_,_,_)),
retractall(complex_type1(_,_)),
retractall(complex_action(_,_,_)),
retractall(complex_predicates(_,_,_)).

get_a_domain(File, 0).
get_a_domain(File, N) :- clean_domain, get_a_domain(File), M is N-1,
 get_a_domain(File, M).


/* for script file r1 */

go :- write(ok), nl,  halt.
go(Args) :- write_ln(Args),
Args = [A1],
string_to_atom(S,A1),
string_to_list(S,L),
write_ln(L), 
halt.
%  concat(Dir,'/',Dir
%  concat(Dir,'/',Dir
%  concat(Dir,'/',Dir1),
%  concat(Dir1,'domain.pddl',D),
%  write(D).
%  create_one_domain(D).


/* create_one_domain: for AIPS2000 - assumes that each domain file has
   exactly one domain description 
   output the processing time to "result"
   output the results to file "domain" in the current directory */

create_one_domain(File_Name) :- 
  statistics(cputime,Time1),
  open(File_Name,read,file_in),
  clean_domain, 
  retractall(count(_)), assert(count(1)),
  get_a_domain(file_in), !,
  domain_name(DName),
  open(domainout,write,out),
  %  write(out '%'), write_ln(out, DName),
  write(out, ':- style_check(-singleton).'), nl(out),
  write(out, ':- style_check(-discontiguous).'), nl(out),
  findall(_, (type(T0,T1),
              write(out,type(T0,T1)), write(out,'.'), nl(out)), _),
%  findall(_, (new_type(NT),
%              write(out, new_type(NT)),
%              write(out,'.'), nl(out)), _),
  findall(_, (complex_predicates(F,F1,FType),
              write(out,complex_predicates(F,F1,FType)), 
              write(out,'.'), nl(out)), _),
  findall(_, (complex_action(F,F1,FType),
              write(out,complex_action(F,F1,FType)), 
              write(out,'.'), nl(out)), _),
  findall(_, (constant(Const0,T2),
              write(out,constant(Const0,T2)), write(out,'.'), nl(out)), _),
  findall(_, (predicates(FName,FVar,FType),
              Fluent =.. [fluent_name | [FName,FVar,FType]],
              write(out,Fluent), write(out,'.'), nl(out)), _),
  findall(_, (action(AName,AVar,AType,_,_),
	      add_a(AVar,AVar1),
              Action =.. [action_name | [AName,AVar1,AType]],
              write(out,Action), write(out,'.'), nl(out)), _),
  retractall(domain(_,_)),
  retractall(auto_domain(_,_)),
  findall(_, (predicates(FName,_,FType),
              auto_arg(FType,Args),
              Fluent1 =.. [fluent_name1 | [FName, Args, FType]],
              write(out,Fluent1), write(out,'.'), nl(out)), _),
  findall(T, (type(T,_),
              findall(TE, auto_domain(T,TE), L),
              findall(Cons, constant(Cons,T),L1),
              union(L,L1,L2),
              write(out,domain(T, [T|L2])), write(out,'.'),nl(out)), _),
  retractall(auto_domain(_,_)),
  findall(_, (action(AName, AArgs, ATypes, Poss, Effs),
              Action =.. [AName | AArgs],
              Poss1 =.. [poss, Action, Poss, []],
              findall(EffA, (member(Eff,Effs),
                            ((Eff =.. [-|[Eff0]], Eff0 =.. [_|EffArgs]);
                             (\+ Eff =.. [-|_], Eff =.. [_|EffArgs])),
                            delete_tuple(AArgs, ATypes, EffArgs,RArgs,RTypes),
                            EffA =.. [effect,Action,Eff,[],[],[RArgs,RTypes]]),
                      EffAs),
              variablize([Poss1,EffAs],AArgs,[Poss2,EffAs1]),
              write(out, Poss2), write(out, '.'), nl(out),
              findall(Eff1, (member(Eff1, EffAs1),
                             write(out, Eff1), write(out, '.'), nl(out)), _)),
           _),
  close(out),
  clean_domain, 
  close(file_in),
%  consult(domainout),
%  solve1(0),
  statistics(cputime,Time2), Time is Time2-Time1,
  write(DName), write(','), 
  write(' domain processing time is '),
  write(Time), nl.


/* create all domains from a pddl file, and writen them into files bearing 
   the same names as the domain names */

create_all_domain(File_Name) :- 
	open(File_Name,read,file_in),
	create_all_domain1(file_in),
	close(file_in).

create_all_domain1(File) :- clean_domain, create_a_domain(File,X), write_ln(X),
  clean_domain, create_all_domain1(File).
create_all_domain1(_).

create_a_domain(File) :- create_a_domain(File,_).

create_a_domain(File,DName) :-
  retractall(count(_)), assert(count(1)),
  get_a_domain(File), !,
  domain_name(DName),
%  term_to_atom(FName,DName),
  open(DName,write,out),
  findall(_, (type(T0,T1),
              write(out,type(T0,T1)), write(out,'.'), nl(out)), _),
  findall(_, (new_type(NT),
              write(out, new_type(NT)),
              write(out,'.'), nl(out)), _),
  findall(_, (complex_predicates(F,F1,FType),
              write(out,complex_predicates(F,F1,FType)), 
              write(out,'.'), nl(out)), _),
  findall(_, (complex_action(F,F1,FType),
              write(out,complex_action(F,F1,FType)), 
              write(out,'.'), nl(out)), _),
  findall(_, (constant(Const0,T2),
              write(out,constant(Const0,T2)), write(out,'.'), nl(out)), _),
  findall(_, (predicates(FName,FVar,FType),
              Fluent =.. [fluent_name | [FName,FVar,FType]],
              write(out,Fluent), write(out,'.'), nl(out)), _),
  findall(_, (action(AName,AVar,AType,_,_),
	      add_a(AVar,AVar1),
              Action =.. [action_name | [AName,AVar1,AType]],
              write(out,Action), write(out,'.'), nl(out)), _),
  retractall(domain(_,_)),
  retractall(auto_domain(_,_)),
  findall(_, (predicates(FName,_,FType),
              auto_arg(FType,Args),
              Fluent1 =.. [fluent_name1 | [FName, Args, FType]],
              write(out,Fluent1), write(out,'.'), nl(out)), _),
  findall(T, (type(T,_),
              findall(TE, auto_domain(T,TE), L),
              findall(Cons, constant(Cons,T),L1),
              union(L,L1,L2),
              write(out,domain(T, [T|L2])), write(out,'.'),nl(out)), _),
  retractall(auto_domain(_,_)),
  findall(_, (action(AName, AArgs, ATypes, Poss, Effs),
              Action =.. [AName | AArgs],
              Poss1 =.. [poss, Action, Poss, []],
              findall(EffA, (member(Eff,Effs),
                            ((Eff =.. [-|[Eff0]], Eff0 =.. [_|EffArgs]);
                             (\+ Eff =.. [-|_], Eff =.. [_|EffArgs])),
                            delete_tuple(AArgs, ATypes, EffArgs,RArgs,RTypes),
                            EffA =.. [effect,Action,Eff,[],[],[RArgs,RTypes]]),
                      EffAs),
              variablize([Poss1,EffAs],AArgs,[Poss2,EffAs1]),
              write(out, Poss2), write(out, '.'), nl(out),
              findall(Eff1, (member(Eff1, EffAs1),
                             write(out, Eff1), write(out, '.'), nl(out)), _)),
           _),
  close(out).

/* add 'a' into a list of variables */

add_a([],[]).
add_a([V|Vs],[V1|Vs1]) :-
	concat(a,V,V1), !,
	add_a(Vs,Vs1).

delete_tuple(As,Ts,[],As,Ts) :- !.
delete_tuple(As,Ts,[A|As1],NewAs,NewTs) :- 
  delete_tuple1(As,Ts,A,As2,Ts2),
  delete_tuple(As2,Ts2,As1,NewAs,NewTs).

delete_tuple1([],[],_,[],[]).
delete_tuple1([A|As],[T|Ts],A,NewAs,NewTs) :- !,
  delete_tuple1(As,Ts,A,NewAs,NewTs).
delete_tuple1([A1|As],[T|Ts],A,[A1|NewAs],[T|NewTs]) :- !,
  delete_tuple1(As,Ts,A,NewAs,NewTs).

/* auto_domain(T,X): if X is a value for type T used in solve1(),
and used_var(A) if A is a variable that has already been used in
Args */

auto_arg(Types,Args) :- retractall(used_var(_)),
  auto_arg1(Types,Args),retractall(used_var(_)).

auto_arg1([],[]).
auto_arg1([T|Types],[A|Args]) :- 
  auto_domain(T,X),
  \+ used_var(X),
  !,
  A=X,
  assert(used_var(A)),
  auto_arg1(Types,Args).
auto_arg1([T|Types],[A|Args]) :- 
  get_new_var(A),
  assert(auto_domain(T,A)),
  assert(used_var(A)),
  auto_arg1(Types,Args).

get_new_var(A) :-
  findall(X, auto_domain(_,X), L),
  length(L,N),
  concat('x',N,A).


get_a_domain(File) :- read_a_domain(File,Domain), !,
  Domain \== -1,
  assert(domain_name(Domain)),
  assert(type(object,object)),
  process_a_domain(File), 
  retractall(complex_type1(_,_)),
  findall(X, ((type(X,_);type(_,X)), \+ type(X,object), 
	assert(type(X,object))),_),
  ((type(X,_), X \== object,
	generate_complex_type,
	process_complex_predicate); a=a),
/*
  discover_type, */
  !.

/* only get STRIPS domains */

process_a_domain(File) :-
  read_a_word(File,C),
  ((C = ')');
   (C = '(',
    read_a_word(File,C1),
    ((C1 = ':requirements',
     process_requirements(File),
     ((req(':adl'),   /* process only STRIPS (non-adl) domains */
       clean_domain,
       get_a_domain(File));
      (\+ req(':adl'),
       process_a_domain(File))));
    (C1 = ':types',
     process_types(File),
     process_a_domain(File));
    (C1 = ':constants',
     process_constants(File),
     process_a_domain(File));
    (C1 = ':predicates',
     process_predicates(File),
     process_a_domain(File));
    (C1 = ':action',
     process_action(File),
     process_a_domain(File))))),
  !.

discover_type :- 
%findall(P1,(predicates(P1,A,B),write(predicates(P1,A,B)),nl),_), !,
  findall(P, (predicates(P, [_], _),
              \+ affected(P), \+ new_type(P),
              assert(new_type(P)), %write(P),nl,
              assert(type(P,object))), L), 
  ((L=[]); (L\==[],update_action_predicate_type)).

/* the predicate P is in the effect list of an action */

affected(P) :- action(_, _, _, _, Effs),
  member(X,Effs),
  (X =.. [P|_];
   (X = -(Y),
    Y =.. [P|_])),
  !.

/* update the type of actions and predicates given the new type */

update_action_predicate_type :- 
/* no new types 
  findall([AName,A,M,P],
   (action(AName, AArgs, ATypes, Poss,_),
    nth_member(A,AArgs,M), nth_member(object,ATypes,M),
    member(X,Poss),
    X =.. [P,A],
    new_type(P)), L),
  findall(AName,
   (action(AName, AArgs, ATypes, Poss,Effs),
    findall([M,P], member([AName,_,M,P],L), L1),
    L1 \== [],
    construct_new_type(L1,ATypes,ATypes1),
    findall(Pre, (member(Pre,Poss), Pre =.. [P|_],
                  member([_,P],L1)), L4),
    subtract(Poss,L4,Poss1),
    assert(temp_action(AName, AArgs, ATypes1, Poss1,Effs))), _),
  retractall(action(_,_,_,_,_)),
  findall(AName, (temp_action(AName, AArgs, ATypes1, Poss,Effs),
                  assert(action(AName, AArgs, ATypes1, Poss,Effs))),_),
*/
  findall(AName,
   (action(AName, AArgs, ATypes, Poss,Effs),
    findall([F,FArgs,FTypes], 
     ((member(Y,Effs);member(Y,Poss)),
      ((Y =.. [-|[Y1]], Y1 =.. [F|FArgs]);
       (Y =.. [F|FArgs], F \== -)),
      get_arg_type(FArgs,FTypes,AArgs,ATypes)), L5),
    sort(L5,L6),
%    retractall(count(_)), assert(count(1)),
    findall([F,FArgs,FTypes], (member([F,FArgs,FTypes],L6),
                               \+ predicates(F,_,FTypes),
                               \+ complex_predicates(F,_,FTypes),
                               count(N),
                               concat(F,N,F1),
                               assert(predicates(F1,FArgs,FTypes)),
                               assert(complex_predicates(F,F1,FTypes)),
                               M is N+1,
                               retractall(count(_)), assert(count(M))), _)),_),
  retractall(temp_action(_,_,_,_,_)),
%  findall([AName,AArgs,ATypes,Poss,Effs],
%   (action(AName, AArgs, ATypes, Poss,Effs),
%    write(action(AName, AArgs, ATypes, Poss,Effs)),nl),_),
  findall([AName,AArgs,ATypes,Poss,Effs],
   (action(AName, AArgs, ATypes, Poss,Effs),
    findall(X, (member(X,Poss), X =.. [F|FArgs], 
                get_arg_type(FArgs,FTypes,AArgs,ATypes),
                complex_predicates(F,F1,FTypes)), L7),                    
    findall(Y, (member(X,Poss), X =.. [F|FArgs], 
                get_arg_type(FArgs,FTypes,AArgs,ATypes),
                complex_predicates(F,F1,FTypes),
                Y =.. [F1|FArgs]), L8),
    subtract(Poss,L7,Poss1),
    union(Poss1,L8,Poss2),
    findall(X, (member(X,Effs), X =.. [-|[Y]],
                Y =.. [F|FArgs], 
                get_arg_type(FArgs,FTypes,AArgs,ATypes),
                complex_predicates(F,F1,FTypes)), L91),
    findall(X, (member(X,Effs), 
                X =.. [F|FArgs], F \== -, 
                get_arg_type(FArgs,FTypes,AArgs,ATypes),
                complex_predicates(F,F1,FTypes)), L92),
    findall(Z, (member(X,Effs), X =.. [-|[Y]],
                Y =.. [F|FArgs], 
                get_arg_type(FArgs,FTypes,AArgs,ATypes),
                complex_predicates(F,F1,FTypes), Z1 =.. [F1|FArgs], Z = -(Z1)), L93),
    findall(Z, (member(X,Effs), 
                X =.. [F|FArgs], F \== -, 
                get_arg_type(FArgs,FTypes,AArgs,ATypes),
                complex_predicates(F,F1,FTypes),Z =.. [F1|FArgs]), L94),
    union(L91,L92,L95), union(L93,L94,L96),
    subtract(Effs,L95,Eff1),
    union(Eff1,L96,Effs2),
    assert(temp_action(AName, AArgs, ATypes, Poss2,Effs2))),_),
  retractall(action(_,_,_,_,_)),
  findall([AName,AArgs, ATypes, Poss,Effs],
   (temp_action(AName, AArgs, ATypes, Poss,Effs),
    assert(action(AName, AArgs, ATypes, Poss,Effs))), _).


/* for each [M,P] in L1, replace Mth element of ATypes by P */

construct_new_type([],ATypes,ATypes).
construct_new_type([[M,P]|L1],ATypes,ATypes1) :- N is M-1,
  append(A1,[_|A2],ATypes), length(A1,N), append(A1,[P|A2],ATypes2), !,
  construct_new_type(L1,ATypes2,ATypes1).

/* given that FArgs is a subset of AArgs, whose type is ATypes, compute the
type of FArgs to FTypes */

get_arg_type([],[],_,_).
get_arg_type([A|FArgs],[T|FTypes],AArgs,ATypes) :-
  nth_member(A,AArgs,N), nth_member(T,ATypes,N), !,
  get_arg_type(FArgs,FTypes,AArgs,ATypes).

    

/* complex_type(X,Y) if Y is a primitive type, and Y is a subtype of X */

complex_type(object,object).
complex_type(X,Y) :- complex_type1(X,Y), \+ complex_type1(Y,_).

generate_complex_type :- type(Y,X), 
	 \+ complex_type1(X,Y), assert(complex_type1(X,Y)), fail.
generate_complex_type :- type(Y,X1), complex_type1(X,X1),
  \+ complex_type1(X,Y), assert(complex_type1(X,Y)), fail.
generate_complex_type.

/* primtive(Ts) if Ts is a list of primitive types */

primitive([]).
primitive([T|Ts]) :- \+ type(_,T), !, primitive(Ts).

/* primitive(Ts1,Ts2): Ts2 is a primitive subtype of Ts1 */

primitive([],[]).
primitive([T1|Ts1], [T2|Ts2]) :- complex_type(T1,T2), primitive(Ts1,Ts2).
primitive([T1|Ts1], [T1|Ts2]) :- primitive([T1]), primitive(Ts1,Ts2).

/* if a predicate has an argument with complex type, then split it into
primitive types */

process_complex_predicate :- 
  findall(X, (predicates(X,Args,Ts),
              \+ primitive(Ts),
%              retractall(count(_)), assert(count(1)),
              findall(T1s, (primitive(Ts,T1s),
                            count(N), concat(X,N,X1),
                            assert(complex_predicates(X,X1,T1s)),
                            retractall(count(_)), M is N+1, assert(count(M))),
                      _)),LX),
  (LX=[]; (LX\==[],
  findall(Y, (complex_predicates(Y,Y1,Ts), predicates(Y,Args,_),
              assert(predicates(Y1,Args,Ts))),_),
  findall(Y, (complex_predicates(Y,_,_), predicates(Y,_,_),
              retractall(predicates(Y,_,_))),_),
  retractall(temp_action(_,_,_,_,_)),
%  findall([X,As, Ts,Poss,Effs], (action(X, As, Ts,Poss,Effs),
%              write_ln(action(X, As, Ts,Poss,Effs))),_),
  findall([X,As, Ts, Poss,Effs], (action(X, As, Ts, Poss,Effs),
              \+ primitive(Ts), 
              findall(T1s, (primitive(Ts,T1s),
                            count(N), concat(X,N,X1),
                            assert(complex_action(X,X1,T1s)),
                            retractall(count(_)), M is N+1, assert(count(M))),
                      _)),_),
  findall(Y, (complex_action(Y,Y1,T1s), action(Y,As,Ts,Poss,Effs), 
              assert(action(Y1,As,T1s,Poss,Effs))),_),
  findall(Y, (complex_action(Y,_,_), action(Y,_,_,_,_),
              retractall(action(Y,_,_,_,_))), _))),
  findall([X,As, Ts,Poss,Effs], (action(X, As, Ts,Poss,Effs),
              convert_list(Poss,Poss1,As,Ts), convert_list(Effs,Effs1,As,Ts),
              assert(temp_action(X,As,Ts,Poss1,Effs1))),_),
  retractall(action(_,_,_,_,_)),
  findall([X, As, Ts,Poss,Effs], (temp_action(X, As, Ts,Poss,Effs),
              assert(action(X, As, Ts,Poss,Effs))),_).
%  findall([X,As, A], (complex_action(X, As, A),
%              write_ln(complex_action(X, As, A))),_),

convert_list([],[],_,_).
convert_list([F|L],[F1|L1],As,T1s) :- convert_literal(F,F1,As,T1s), !,
  convert_list(L,L1,As,T1s).

convert_literal(-F, -F1, As, Ts) :- !,
  convert_literal(F, F1, As, Ts).
convert_literal(F, F1, As, Ts) :- 
  F =.. [P|A], construct_arg_type(A,As,Ts,T1s),
  convert_literal1(F, F1, T1s).

/* convert_literal1(F, F1, T1s): given that T1s is the type of the arguments
of F, convert F into F1 according to complex_predicates */

convert_literal1(-F, -F1, Ts) :- !,
  convert_literal1(F, F1, Ts).
convert_literal1(F, F1, Ts) :- F =.. [P|A],
  complex_predicates(P,P1,Ts), !, F1 =.. [P1|A].
convert_literal1(F, F, _).

/*   construct_arg_type(As,As1,Ts,T1s): find out the type of As (T1s) given
that Ts is the type of As1, and that the elements in As either is a constant,
or occurrs in As1 */

construct_arg_type([],_,_,[]).
construct_arg_type([A|As],As1,Ts,[T|T1s]) :-
  nth0(N,As1,A), !,
  nth0(N,Ts,T),
  construct_arg_type(As,As1,Ts,T1s).
construct_arg_type([A|As],As1,Ts,[T|T1s]) :-
  constant(A,T), !,
  construct_arg_type(As,As1,Ts,T1s).



process_requirements(File) :-
  read_a_word(File,C),
  (C = ')';
   (assert(req(C)),
    process_requirements(File))),
  !.

process_types(File) :-
  read_a_word(File,C),
  ((C = ')', 
    findall(X2, (temp_type(X2), assert(type(X2,object))),_),
    retractall(temp_type(_)));
   (C = '-', 
    read_a_word(File,T),
    findall(X1, (temp_type(X1), 
                 assert(type(X1,T))), _),
    retractall(temp_type(_)),
    process_types(File));
   (assert(temp_type(C)),
    process_types(File))),
  !.
  
process_constants(File) :-
  read_a_word(File,C),
  ((C = ')', 
    findall(X2, (temp_type(X2), assert(constant(X2,object))),_),
    retractall(temp_type(_)));
   (C = '-', 
    read_a_word(File,T),
    findall(X1, (temp_type(X1), 
                 assert(constant(X1,T))), _),
    retractall(temp_type(_)),
    process_constants(File));
   (assert(temp_type(C)),
    process_constants(File))),
  !.

process_predicates(File) :-
  read_a_word(File,C),
  (C = ')';
   (C = '(',
    read_a_predicate(File),
    process_predicates(File))),
  !.

read_a_predicate(File) :-
  read_a_word(File,Name),
  read_args(File,[],Args,Types),
  reverse(Args,Args1), reverse(Types,Types1),
  assert(predicates(Name,Args1,Types1)).

read_args(File,TempArgs,Args,Types) :-
  read_a_word(File,A),
  ((A = '-',
    read_a_word(File,T),
    length(TempArgs,N),
    n_list(T,Ts,N),
    read_args(File,[],Args1,Types1),
    append(Types1,Ts,Types),
    append(Args1,TempArgs,Args));
   (A = ')',
    ((TempArgs = [],Args=[],Types=[]);
     (TempArgs \== [], 
      length(TempArgs,N),
      n_list('object',Types,N),
      Args = TempArgs)));
   read_args(File,[A|TempArgs],Args,Types)),
  !.

n_list(X, [X],1).
n_list(X, [X|Xs],N) :- M is N-1, n_list(X,Xs,M).

process_action(File) :- 
  read_a_word(File,Name),
  assert(name(Name)),
  process_action1(File).

process_action1(File) :-
  read_a_word(File,C),
  ((C = ':parameters',
    read_a_word(File,_),
    read_args(File,[],Args1,Types1),
    reverse(Args1,Args),    reverse(Types1,Types),
    assert(args(Args)),
    assert(temp_type(Types)),
    process_action1(File));
   (C = ':precondition',
    get_goal(File,Precond),
    assert(poss(Precond)),
    process_action1(File));
   (C = ':effect',
    get_goal(File,Effect),
    assert(eff(Effect)),
    process_action1(File));
   (C = ')',
    name(Name),
    (args(A); (\+ args(_), A=[])),
    (temp_type(T); (\+ temp_type(_), T=[])),
    (poss(P); (\+ poss(_), P=[])),
    eff(E),
    assert(action(Name,A,T,P,E)),
    retractall(name(_)),
    retractall(args(_)),
    retractall(temp_type(_)),
    retractall(poss(_)),
    retractall(eff(_)))),
  !.  
    
    
  

/* read the file until either a problem description is found, or the end
   of the file is reached */

%(define (problem mysty-x-1)

read_a_problem(File,Problem) :- 
  read_a_word(File,X),
  ((X = -1, Problem = -1);
   (X = '(',
    read_a_word(File,'define'),
    read_a_word(File,'('),
    read_a_word(File,'problem'),
    read_a_word(File,Problem), 
    read_a_word(File,')'))),
  !.
read_a_problem(File,Problem) :- 
  read_a_problem(File,Problem).


/* read from a file a complete problem description: Problem_Name, action
Domain_name, Domain of types (of the format:
  [[T1,[o1,o2,...],...,[Tn,[l1,l2,...]]]), Init (the list of facts true in 
the initial situation, and Goal (a list of atoms) */
/*
(define (problem mysty-x-1)
   (:domain mystery-typed)
   (:objects rice pear flounder okra pork lamb - food
             mars earth uranus venus - planet)
   (:init (eats lamb pork)
          (eats pork okra))
   (:goal (and (craves abrasion rice))))
or
(define (problem mprime-x-1)
        (:domain mystery-prime-typed)
	(:situation mysty-x-1)
	(:goal (and (craves abrasion rice))))
*/

:- dynamic temp_dname/1, temp_pname/1, temp_domain/1, temp_init/1,
	temp_goal/1.

get_a_problem(File) :-
	retractall(temp_dname(_)),
	retractall(temp_pname(_)), 
	retractall(temp_domain(_)), retractall(temp_init(_)),
	retractall(temp_goal(_)),
  read_a_problem(File,Problem_Name),
  Problem_Name \== -1,
  read_a_word(File,_),  read_a_word(File,':domain'),
  read_a_word(File,Domain_Name),
  assert(temp_pname(Problem_Name)),
  assert(temp_dname(Domain_Name)),
  get_a_problem1(File).

get_a_problem1(File) :-
  read_a_word(File,X),
  ((X=':situation',
    read_a_word(File,Sit_Name),
    problem(Sit_Name,_,Domain1,Init1,_),
    read_a_word(File,_),   read_a_word(File,_),
    read_a_word(File,X1),
    ((X1=':init',get_init(File,Init2),
      read_a_word(File,_),read_a_word(File,_));
     (Init2=[])),
    union(Init1,Init2,Init3),
    get_goal(File,Goal), temp_pname(Problem_Name),temp_dname(Domain_Name),
    assert(problem(Problem_Name,Domain_Name,Domain1,Init3,Goal)));
   (X=':objects',
    get_object_domain(File,Domain2), assert(temp_domain(Domain2)),
    get_a_problem1(File));
   (X = ':init',
    get_init(File,Init4), assert(temp_init(Init4)),
    get_a_problem1(File));
   (X = ':goal',
    get_goal(File,Goal1), 
    temp_pname(Problem_Name),temp_dname(Domain_Name),
    temp_init(Init4),temp_domain(Domain2),
    assert(problem(Problem_Name,Domain_Name,Domain2,Init4,Goal1)));
   get_a_problem1(File)),
	retractall(temp_dname(_)),
	retractall(temp_pname(_)), 
	retractall(temp_domain(_)), retractall(temp_init(_)),
	retractall(temp_goal(_)),
   !.

/* get all problems from a file_name */

get_all_problem(File_Name) :-
	open(File_Name,read,in_file),
	retractall(problem(_,_,_,_,_)),
	get_all_problem1(in_file),
	close(in_file).

/* get_all_problem1(File) : get all the problems in a pddl file */

get_all_problem1(File) :- get_a_problem(File), !, get_all_problem1(File).
get_all_problem1(_) :- !.

/*
get_a_problem(File,DName,PName,Domains,Init,Goal) - get a problem for
action domain DName
*/

get_a_problem(File,DName,PName,Domains,Init,Goal) :-
    get_a_problem(File),
    (problem(PName,DName,Domains,Init,Goal);
     get_a_problem(File,DName,PName,Domains,Init,Goal)).

/*
 rice pear flounder okra pork lamb - food
             rest - pleasure)
 rice pear flounder okra pork lamb rest hangover) %for STRIPS without type
*/

get_object_domain(File,Domains) :- get_object_domain(File,Domains,[],[]).

get_object_domain(File,Domains,Domains1,Domain) :- 
    read_a_word(File,X),
    ((X=')',
      ((Domains1=[],Domains=[[object,Domain]]);
       (Domains1\==[], Domains=Domains1)));
     (X='-',
      read_a_word(File,Type),
      get_object_domain(File,Domains,[[Type,Domain]|Domains1],[]));
     get_object_domain(File,Domains,Domains1,[X|Domain])),
    !.

/*
    (eats lamb pork)
    (eats pork okra)
    (locale okra guanabara)
    )
*/

get_init(File,Init) :- 
    read_a_word(File,X),
    ((X='(',
      get_an_atom_list(File,List),
      Atom =.. List,
      get_init(File,Init1),
      Init=[Atom|Init1]);
     (X=')', Init=[])),
    !.

/* craves grds gts-2) => [craves, grds, gts-2] */

get_an_atom_list(File,List) :-
    read_a_word(File,X),
    ((X=')',
      List=[]);
     (get_an_atom_list(File,List1),
      List=[X|List1])),
    !.

/*
 (and (not (craves grief-7 beef))
               (craves depression-1 beef))  => 
                 [- craves(grief-7,beef), craves(depression-1,beef)]
or
 (craves g s) => [craves(g,s)]
or
 (not (craves g s)) => [- craves(g,s)]
*/

get_goal(File,Goal) :-
    read_a_word(File,_),
    read_a_word(File,C),
    ((C = 'and',
      read_a_word(File,_),
      get_goal1(File,Goal));
     (C = 'not',
      read_a_word(File,_),
      get_an_atom_list(File,List),
      Atom =.. List,
      Goal = [-(Atom)],
      read_a_word(File,_));
     (get_an_atom_list(File,List),
      Atom =.. [C | List],
      Goal = [Atom])),
    !.

/* 
not (craves grief-7 beef))
               (craves depression-1 beef))  => 
                 [- craves(grief-7,beef), craves(depression-1,beef)]
craves grief-7 beef))
               (not (craves depression-1 beef)))  => 
                 [craves(grief-7,beef),- craves(depression-1,beef)]
*/

get_goal1(File,Goal) :-
    read_a_word(File,C),
    ((C = 'not',
     read_a_word(File,_),
     get_an_atom_list(File,List),
     Atom1 =.. List,
     Atom = -(Atom1),
     read_a_word(File,_));
    (get_an_atom_list(File,List),
     Atom =.. [C | List])),
    read_a_word(File,X),
    ((X='(',
      get_goal1(File,Goal1),
      Goal=[Atom|Goal1]);
     (X=')',
      Goal=[Atom])),
    !.

cleanup_problem :- retractall(problem(_,_,_,_,_)).
