timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile01 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile02 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile03 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile04 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile05 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile06 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile07 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile08 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile09 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile10 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile11 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile12 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile13 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile14 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile15 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile16 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile17 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile18 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile19 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile20 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile21 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile22 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile23 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile24 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile25 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile26 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile27 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile28 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile29 -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile30 -speed -noout
