INSERT INTO dominios VALUES(1,"Blocks World");
INSERT INTO dominios VALUES(2,"Depot");
INSERT INTO dominios VALUES(3,"Driver Log");
INSERT INTO dominios VALUES(4,"Gripper");
INSERT INTO dominios VALUES(5,"Logistic World");
INSERT INTO dominios VALUES(6,"Mystery");
INSERT INTO dominios VALUES(7,"Pathways");
INSERT INTO dominios VALUES(8,"Pipes World");
INSERT INTO dominios VALUES(9,"Satellite");
INSERT INTO dominios VALUES(10,"TPP");

INSERT INTO planejadores VALUES(1,"Blackbox");
INSERT INTO planejadores VALUES(2,"IPP");
INSERT INTO planejadores VALUES(3,"FF");
INSERT INTO planejadores VALUES(4,"R");
INSERT INTO planejadores VALUES(5,"LPG");
INSERT INTO planejadores VALUES(6,"Fast Downward");
INSERT INTO planejadores VALUES(7,"YAHSP");
INSERT INTO planejadores VALUES(8,"SGPlan");
INSERT INTO planejadores VALUES(9,"SATPlan");
INSERT INTO planejadores VALUES(10,"MAXPlan");

INSERT INTO caracteristicas VALUES(1,"Número de Atores");
INSERT INTO caracteristicas VALUES(2,"Número de Casos de Uso");
INSERT INTO caracteristicas VALUES(3,"Número Medio de Atores por Caso de Uso");
INSERT INTO caracteristicas VALUES(4,"Número total de Classes");
INSERT INTO caracteristicas VALUES(5,"Número total de Atributos");
INSERT INTO caracteristicas VALUES(6,"Número total de Métodos");
INSERT INTO caracteristicas VALUES(7,"Número total de Associações");
INSERT INTO caracteristicas VALUES(8,"Número total de Agregação (pares todo-parte)");
INSERT INTO caracteristicas VALUES(9,"Número total de Generalização (pares pai-filho)");
INSERT INTO caracteristicas VALUES(10,"Número total de Hierarquias");
INSERT INTO caracteristicas VALUES(11,"Caminho mais longo entre uma classe e sua raiz");
INSERT INTO caracteristicas VALUES(12,"Caminho mais longo de uma agregação até a folha");
INSERT INTO caracteristicas VALUES(13,"Número total de estados");
INSERT INTO caracteristicas VALUES(14,"Número total de ações de entrada");
INSERT INTO caracteristicas VALUES(15,"Número total de açoes de saída");
INSERT INTO caracteristicas VALUES(16,"Número total de ações");
INSERT INTO caracteristicas VALUES(17,"Número total de transições");


INSERT INTO tecnicas VALUES(1,"State-Space");
INSERT INTO tecnicas VALUES(2,"Plan-Space");
INSERT INTO tecnicas VALUES(3,"Partial-order");
INSERT INTO tecnicas VALUES(4,"Total-order");
INSERT INTO tecnicas VALUES(5,"Linear");
INSERT INTO tecnicas VALUES(6,"Non-Linear");
INSERT INTO tecnicas VALUES(7,"Hierarchical");
INSERT INTO tecnicas VALUES(8,"Forward-chaining");
INSERT INTO tecnicas VALUES(9,"Backward-chaining");
INSERT INTO tecnicas VALUES(10,"Graph-based");
INSERT INTO tecnicas VALUES(11,"Knowledge-based");
INSERT INTO tecnicas VALUES(12,"SAT-based");
INSERT INTO tecnicas VALUES(13,"Heurist Search");

-- Blackbox --
INSERT INTO dominios_caracteristicas VALUES(1,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(1,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,4,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(1,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,7,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(1,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,9,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(1,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(1,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(1,12,"Alto");
INSERT INTO dominios_caracteristicas VALUES(1,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,14,"Alto");
INSERT INTO dominios_caracteristicas VALUES(1,15,"Alto");
INSERT INTO dominios_caracteristicas VALUES(1,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(1,17,"Medio");

-- Depots --
INSERT INTO dominios_caracteristicas VALUES(2,1,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(2,3,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,4,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(2,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(2,7,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(2,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(2,9,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,10,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,11,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(2,13,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,14,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,15,"Alto");
INSERT INTO dominios_caracteristicas VALUES(2,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(2,17,"Alto");

-- Driverlog --
INSERT INTO dominios_caracteristicas VALUES(3,1,"Alto");
INSERT INTO dominios_caracteristicas VALUES(3,2,"Alto");
INSERT INTO dominios_caracteristicas VALUES(3,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,6,"Alto");
INSERT INTO dominios_caracteristicas VALUES(3,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,10,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,11,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(3,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(3,16,"Alto");
INSERT INTO dominios_caracteristicas VALUES(3,17,"Medio");

-- Gripper --
INSERT INTO dominios_caracteristicas VALUES(4,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,2,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(4,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(4,5,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,6,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,7,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(4,9,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(4,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(4,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(4,16,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(4,17,"Medio");

-- Logistic --
INSERT INTO dominios_caracteristicas VALUES(5,1,"Alto");
INSERT INTO dominios_caracteristicas VALUES(5,2,"Alto");
INSERT INTO dominios_caracteristicas VALUES(5,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,6,"Alto");
INSERT INTO dominios_caracteristicas VALUES(5,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,8,"Alto");
INSERT INTO dominios_caracteristicas VALUES(5,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,10,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,11,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,12,"Alto");
INSERT INTO dominios_caracteristicas VALUES(5,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(5,15,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(5,16,"Alto");
INSERT INTO dominios_caracteristicas VALUES(5,17,"Medio");

-- Mystery --
INSERT INTO dominios_caracteristicas VALUES(6,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,2,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,6,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,7,"Alto");
INSERT INTO dominios_caracteristicas VALUES(6,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,10,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,11,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,13,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,14,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,15,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,16,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,17,"Baixo");

-- Pathways --
INSERT INTO dominios_caracteristicas VALUES(7,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,8,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,10,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,11,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,17,"Baixo");

-- Pipes --
INSERT INTO dominios_caracteristicas VALUES(8,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,2,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,3,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,5,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,6,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,9,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,16,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,17,"Medio");

-- Satellite -- 
INSERT INTO dominios_caracteristicas VALUES(9,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,9,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,12,"Alto");
INSERT INTO dominios_caracteristicas VALUES(9,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,17,"Alto");

-- TPP -- 
INSERT INTO dominios_caracteristicas VALUES(10,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,7,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,10,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,11,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,12,"Alto");
INSERT INTO dominios_caracteristicas VALUES(10,13,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,14,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,17,"Baixo");


INSERT INTO planejadores_tecnicas VALUES(1,1);
INSERT INTO planejadores_tecnicas VALUES(2,1);
INSERT INTO planejadores_tecnicas VALUES(3,1);
INSERT INTO planejadores_tecnicas VALUES(4,1);
INSERT INTO planejadores_tecnicas VALUES(6,1);
INSERT INTO planejadores_tecnicas VALUES(7,1);
INSERT INTO planejadores_tecnicas VALUES(5,2);
INSERT INTO planejadores_tecnicas VALUES(8,2);
INSERT INTO planejadores_tecnicas VALUES(9,2);
INSERT INTO planejadores_tecnicas VALUES(10,2);
INSERT INTO planejadores_tecnicas VALUES(4,3);
INSERT INTO planejadores_tecnicas VALUES(5,3);
INSERT INTO planejadores_tecnicas VALUES(8,3);
INSERT INTO planejadores_tecnicas VALUES(9,3);
INSERT INTO planejadores_tecnicas VALUES(10,3);
INSERT INTO planejadores_tecnicas VALUES(1,4);
INSERT INTO planejadores_tecnicas VALUES(2,4);
INSERT INTO planejadores_tecnicas VALUES(3,4);
INSERT INTO planejadores_tecnicas VALUES(6,4);
INSERT INTO planejadores_tecnicas VALUES(7,4);
INSERT INTO planejadores_tecnicas VALUES(1,5);
INSERT INTO planejadores_tecnicas VALUES(2,5);
INSERT INTO planejadores_tecnicas VALUES(3,5);
INSERT INTO planejadores_tecnicas VALUES(6,5);
INSERT INTO planejadores_tecnicas VALUES(7,5);
INSERT INTO planejadores_tecnicas VALUES(4,6);
INSERT INTO planejadores_tecnicas VALUES(5,6);
INSERT INTO planejadores_tecnicas VALUES(8,6);
INSERT INTO planejadores_tecnicas VALUES(9,6);
INSERT INTO planejadores_tecnicas VALUES(10,6);
INSERT INTO planejadores_tecnicas VALUES(6,7);
INSERT INTO planejadores_tecnicas VALUES(1,8);
INSERT INTO planejadores_tecnicas VALUES(3,8);
INSERT INTO planejadores_tecnicas VALUES(4,8);
INSERT INTO planejadores_tecnicas VALUES(5,8);
INSERT INTO planejadores_tecnicas VALUES(6,8);
INSERT INTO planejadores_tecnicas VALUES(7,8);
INSERT INTO planejadores_tecnicas VALUES(4,9);
INSERT INTO planejadores_tecnicas VALUES(1,10);
INSERT INTO planejadores_tecnicas VALUES(2,10);
INSERT INTO planejadores_tecnicas VALUES(3,10);
INSERT INTO planejadores_tecnicas VALUES(5,10);
INSERT INTO planejadores_tecnicas VALUES(7,10);
INSERT INTO planejadores_tecnicas VALUES(9,10);
INSERT INTO planejadores_tecnicas VALUES(10,10);
INSERT INTO planejadores_tecnicas VALUES(7,11);
INSERT INTO planejadores_tecnicas VALUES(1,12);
INSERT INTO planejadores_tecnicas VALUES(9,12);
INSERT INTO planejadores_tecnicas VALUES(10,12);
INSERT INTO planejadores_tecnicas VALUES(3,13);
INSERT INTO planejadores_tecnicas VALUES(6,13);
INSERT INTO planejadores_tecnicas VALUES(7,13);cteristicas VALUES(5,20,"Alto");
INSERT INTO dominios_caracteristicas VALUES(6,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,4,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,5,"Alto");
INSERT INTO dominios_caracteristicas VALUES(6,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(6,7,"Alto");
INSERT INTO dominios_caracteristicas VALUES(6,8,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,9,"Alto");
INSERT INTO dominios_caracteristicas VALUES(6,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,13,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,14,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,15,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,16,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,17,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,18,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,19,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(6,20,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,3,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,4,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,5,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,13,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,14,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,15,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(7,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,17,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,18,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,19,"Medio");
INSERT INTO dominios_caracteristicas VALUES(7,20,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,2,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,3,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,4,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,5,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,7,"Alto");
INSERT INTO dominios_caracteristicas VALUES(8,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,13,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,14,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,15,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(8,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,17,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,18,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,19,"Medio");
INSERT INTO dominios_caracteristicas VALUES(8,20,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,3,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,4,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,5,"Alto");
INSERT INTO dominios_caracteristicas VALUES(9,6,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,7,"Alto");
INSERT INTO dominios_caracteristicas VALUES(9,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,9,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,13,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,14,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(9,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,17,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,18,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,19,"Medio");
INSERT INTO dominios_caracteristicas VALUES(9,20,"Alto");
INSERT INTO dominios_caracteristicas VALUES(10,1,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,2,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,3,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,4,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,5,"Alto");
INSERT INTO dominios_caracteristicas VALUES(10,6,"Alto");
INSERT INTO dominios_caracteristicas VALUES(10,7,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,8,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,9,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,10,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,11,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,12,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,13,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,14,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,15,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,16,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,17,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,18,"Baixo");
INSERT INTO dominios_caracteristicas VALUES(10,19,"Medio");
INSERT INTO dominios_caracteristicas VALUES(10,20,"Baixo");

INSERT INTO planejadores_tecnicas VALUES(1,1);
INSERT INTO planejadores_tecnicas VALUES(2,1);
INSERT INTO planejadores_tecnicas VALUES(3,1);
INSERT INTO planejadores_tecnicas VALUES(4,1);
INSERT INTO planejadores_tecnicas VALUES(6,1);
INSERT INTO planejadores_tecnicas VALUES(7,1);
INSERT INTO planejadores_tecnicas VALUES(5,2);
INSERT INTO planejadores_tecnicas VALUES(8,2);
INSERT INTO planejadores_tecnicas VALUES(9,2);
INSERT INTO planejadores_tecnicas VALUES(10,2);
INSERT INTO planejadores_tecnicas VALUES(4,3);
INSERT INTO planejadores_tecnicas VALUES(5,3);
INSERT INTO planejadores_tecnicas VALUES(8,3);
INSERT INTO planejadores_tecnicas VALUES(9,3);
INSERT INTO planejadores_tecnicas VALUES(10,3);
INSERT INTO planejadores_tecnicas VALUES(1,4);
INSERT INTO planejadores_tecnicas VALUES(2,4);
INSERT INTO planejadores_tecnicas VALUES(3,4);
INSERT INTO planejadores_tecnicas VALUES(6,4);
INSERT INTO planejadores_tecnicas VALUES(7,4);
INSERT INTO planejadores_tecnicas VALUES(1,5);
INSERT INTO planejadores_tecnicas VALUES(2,5);
INSERT INTO planejadores_tecnicas VALUES(3,5);
INSERT INTO planejadores_tecnicas VALUES(6,5);
INSERT INTO planejadores_tecnicas VALUES(7,5);
INSERT INTO planejadores_tecnicas VALUES(4,6);
INSERT INTO planejadores_tecnicas VALUES(5,6);
INSERT INTO planejadores_tecnicas VALUES(8,6);
INSERT INTO planejadores_tecnicas VALUES(9,6);
INSERT INTO planejadores_tecnicas VALUES(10,6);
INSERT INTO planejadores_tecnicas VALUES(6,7);
INSERT INTO planejadores_tecnicas VALUES(1,8);
INSERT INTO planejadores_tecnicas VALUES(3,8);
INSERT INTO planejadores_tecnicas VALUES(4,8);
INSERT INTO planejadores_tecnicas VALUES(5,8);
INSERT INTO planejadores_tecnicas VALUES(6,8);
INSERT INTO planejadores_tecnicas VALUES(7,8);
INSERT INTO planejadores_tecnicas VALUES(4,9);
INSERT INTO planejadores_tecnicas VALUES(1,10);
INSERT INTO planejadores_tecnicas VALUES(2,10);
INSERT INTO planejadores_tecnicas VALUES(3,10);
INSERT INTO planejadores_tecnicas VALUES(5,10);
INSERT INTO planejadores_tecnicas VALUES(7,10);
INSERT INTO planejadores_tecnicas VALUES(9,10);
INSERT INTO planejadores_tecnicas VALUES(10,10);
INSERT INTO planejadores_tecnicas VALUES(7,11);
INSERT INTO planejadores_tecnicas VALUES(1,12);
INSERT INTO planejadores_tecnicas VALUES(9,12);
INSERT INTO planejadores_tecnicas VALUES(10,12);
INSERT INTO planejadores_tecnicas VALUES(3,13);
INSERT INTO planejadores_tecnicas VALUES(6,13);
INSERT INTO planejadores_tecnicas VALUES(7,13);

INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,1,25.4,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,2,0,0);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,3,60,6);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,4,10,1);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,5,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,6,44,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,7,13.33,1);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,8,10,1);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,9,95,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(1,10,26.67,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,1,26.73,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,2,45.45,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,3,65,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,4,25,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,5,64.29,6);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,6,43.33,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,7,16.67,2);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,8,16,2);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,9,35,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(2,10,26.67,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,1,72.55,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,2,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,3,75,8);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,4,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,5,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,6,53.33,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,7,33.33,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,8,40,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,9,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(3,10,40,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,1,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,2,4.55,0);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,3,25,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,4,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,6,13.33,1);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,7,0,0);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,8,0,0);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,9,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(4,10,66.67,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,1,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,2,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,3,90,9);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,4,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,6,60,6);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,7,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,8,68,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,9,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(5,10,46.67,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,1,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,2,86.36,9);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,3,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,4,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,6,63.33,6);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,7,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,8,38,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,9,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(6,10,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,1,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,2,86.36,9);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,3,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,4,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,6,53.33,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,7,66.67,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,8,86,9);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,9,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(7,10,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,1,94.29,9);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,2,95.45,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,3,85,9);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,4,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,6,53.33,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,7,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,8,66,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,9,83.33,8);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(8,10,100,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,1,97.14,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,2,72.73,7);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,3,80,8);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,4,20,2);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,6,56.67,6);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,7,30,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,8,24,2);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,9,30.55,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(9,10,80,8);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,1,37.14,4);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,2,50,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,3,55,6);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,4,15,2);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,5,96.43,10);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,6,50,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,7,50,5);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,8,16,2);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,9,30,3);
INSERT INTO planejamentos (planejador_id,dominio_id,eficiencia,nota) VALUES(10,10,50,5);












