timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile1.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile2.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile3.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile4.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile5.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile6.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile7.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile8.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile9.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile10.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile11.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile12.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile13.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile14.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile15.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile16.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile17.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile18.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile19.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/gripper/domain.pddl -f /home/matheus/mestrado/comp/gripper/pfile20.pddl -speed -noout
