timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p01.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p02.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p03.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p04.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p05.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p06.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p07.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p08.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p09.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p10.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p11.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p12.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p13.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p14.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p15.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p16.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p17.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p18.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p19.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p20.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p21.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p22.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p23.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p24.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p25.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p26.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p27.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p28.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p29.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p30.pddl -speed -noout
