timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p01.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p01.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p02.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p02.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p03.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p03.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p04.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p04.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p05.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p05.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p06.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p06.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p07.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p07.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p08.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p08.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p09.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p09.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p10.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p10.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p11.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p11.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p12.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p12.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p13.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p13.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p14.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p14.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p15.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p15.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p16.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p16.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p17.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p17.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p18.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p18.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p19.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p19.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p20.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p20.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p21.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p21.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p22.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p22.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p23.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p23.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p24.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p24.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p25.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p25.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p26.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p26.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p27.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p27.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p28.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p28.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p29.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p29.pddl -speed -noout
timeout 1200 ./lpg-td-1.0 -o /home/matheus/mestrado/comp/tpp/Strips/domain_p30.pddl -f /home/matheus/mestrado/comp/tpp/Strips/p30.pddl -speed -noout
