timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile1
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile2
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile3
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile4
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile5
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile6
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile7
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile8
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile9
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile10
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile11
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile12
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile13
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile14
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile15
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile16
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile17
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile18
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile19
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/sattelite/antigo/domain.pddl -f /home/matheus/mestrado/comp/sattelite/antigo/pfile20
