timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p01.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p02.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p03.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p04.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p05.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p06.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p07.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p08.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p09.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p10.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p11.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p12.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p13.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p14.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p15.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p16.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p17.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p18.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p19.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p20.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p21.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p22.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p23.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p24.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p25.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p26.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p27.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p28.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p29.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p30.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p31.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p32.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p33.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p34.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p35.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p36.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p37.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p38.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p39.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p40.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p41.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p42.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p43.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p44.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p45.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p46.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p47.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p48.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p49.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pipesworld/domain.pddl -f /home/matheus/mestrado/comp/pipesworld/p50.pddl
