./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile1
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile2
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile3
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile4
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile5
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile6
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile7
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile8
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile9
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile10
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile11
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile12
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile13
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile14
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile15
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile16
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile17
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile18
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile19
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile20
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile21
./blackbox -o /home/matheus/mestrado/comp/depots/domain.pddl -f /home/matheus/mestrado/comp/depots/pfile22
