timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile1
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile2
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile3
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile4
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile5
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile6
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile7
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile8
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile9
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile10
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile11
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile12
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile13
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile14
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile15
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile16
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile17
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile18
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile19
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile20
