timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p01.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p01.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p02.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p02.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p03.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p03.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p04.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p04.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p05.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p05.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p06.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p06.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p07.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p07.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p08.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p08.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p09.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p09.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p10.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p10.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p11.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p11.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p12.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p12.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p13.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p13.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p14.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p14.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p15.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p15.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p16.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p16.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p17.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p17.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p18.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p18.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p19.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p19.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p20.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p20.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p21.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p21.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p22.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p22.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p23.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p23.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p24.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p24.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p25.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p25.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p26.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p26.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p27.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p27.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p28.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p28.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p29.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p29.pddl
timeout 1200 ./ipp -o /home/matheus/mestrado/comp/pathways/Strips/domain_p30.pddl -f /home/matheus/mestrado/comp/pathways/Strips/p30.pddl
