timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile1.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile2.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile3.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile4.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile5.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile6.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile7.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile8.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile9.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile10.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile11.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile12.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile13.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile14.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile15.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile16.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile17.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile18.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile19.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/gripper/ -o domain.pddl -f pfile20.pddl
