timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile01;
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile02
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile03
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile04
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile05
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile06
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile07
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile08
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile09
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile10
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile11
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile12
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile13
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile14
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile15
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile16
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile17
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile18
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile19
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile20
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile21
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile22
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile23
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile24
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile25
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile26
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile27
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile28
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile29
timeout 1200 ./ff -p /home/matheus/mestrado/comp/mystery/ -o domain.pddl -f pfile30
