timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p01.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p02.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p03.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p04.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p05.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p06.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p07.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p08.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p09.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p10.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p11.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p12.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p13.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p14.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p15.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p16.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p17.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p18.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p19.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p20.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p21.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p22.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p23.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p24.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p25.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p26.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p27.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p28.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p29.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p30.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p31.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p32.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p33.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p34.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p35.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p36.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p37.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p38.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p39.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p40.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p41.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p42.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p43.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p44.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p45.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p46.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p47.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p48.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p49.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/pipesworld/ -o domain.pddl -f p50.pddl
