timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p01.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p02.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p03.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p04.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p05.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p06.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p07.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p08.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p09.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p10.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p11.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p12.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p13.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p14.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p15.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p16.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p17.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p18.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p19.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p20.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p21.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p22.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p23.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p24.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p25.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p26.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p27.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p28.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p29.pddl
timeout 1200 ./blackbox -o /home/matheus/mestrado/comp/storage/domain.pddl -f /home/matheus/mestrado/comp/storage/p30.pddl
