timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p01.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p02.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p03.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p04.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p05.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p06.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p07.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p08.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p09.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p10.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p11.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p12.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p13.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p14.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p15.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p16.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p17.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p18.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p19.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p20.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p21.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p22.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p23.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p24.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p25.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p26.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p27.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p28.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p29.pddl
timeout 1200 ./ff -p /home/matheus/mestrado/comp/storage/ -o domain.pddl -f p30.pddl
