timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P01_PFILE1.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P02_PFILE2.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P03_PFILE3.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P04_PFILE4.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P05_PFILE5.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P06_PFILE6.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P07_PFILE7.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P08_PFILE8.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P09_PFILE9.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P10_PFILE10.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P11_PFILE11.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P12_PFILE12.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P13_PFILE13.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P14_PFILE14.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P15_PFILE15.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P16_PFILE16.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P17_PFILE17.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P18_PFILE18.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P19_PFILE19.PDDL
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/sattelite/DOMAIN.PDDL -f /home/matheus/mestrado/comp/sattelite/P20_PFILE20.PDDL
