timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile01
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile02
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile03
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile04
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile05
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile06
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile07
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile08
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile09
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile10
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile11
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile12
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile13
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile14
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile15
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile16
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile17
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile18
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile19
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile20
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile21
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile22
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile23
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile24
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile25
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile26
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile27
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile28
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile29
timeout 1200 ./maxplan -o /home/matheus/mestrado/comp/mystery/domain.pddl -f /home/matheus/mestrado/comp/mystery/pfile30
