./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile1
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile2
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile3
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile4
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile5
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile6
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile7
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile8
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile9
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile10
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile11
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile12
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile13
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile14
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile15
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile16
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile17
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile18
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile19
./blackbox -o /home/matheus/mestrado/comp/driverlog/domain.pddl -f /home/matheus/mestrado/comp/driverlog/pfile20
