timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile1
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile2
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile3
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile4
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile5
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile6
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile7
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile8
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile9
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile10
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile11
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile12
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile13
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile14
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile15
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile16
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile17
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile18
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile19
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile20
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile21
timeout 1200 ./yahsp /tmp/mestrado/depots/domain.pddl /tmp/mestrado/depots/pfile22
