timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-4-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-4-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-4-2.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-5-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-5-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-5-2.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-6-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-6-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-6-2.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-6-3.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-7-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-7-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-8-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-8-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-9-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-9-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-10-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-10-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-11-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-11-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-12-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-12-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-13-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-13-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-14-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-14-1.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-15-0.pddl
timeout 1200 ./yahsp /tmp/mestrado/logistic/domain.pddl /tmp/mestrado/logistic/probLOGISTICS-15-1.pddl
