timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile1
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile2
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile3
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile4
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile5
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile6
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile7
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile8
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile9
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile10
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile11
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile12
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile13
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile14
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile15
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile16
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile17
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile18
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile19
timeout 1200 ./yahsp /tmp/mestrado/driverlog/domain.pddl /tmp/mestrado/driverlog/pfile20
