timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p01.pddl /home/matheus/mestrado/comp/tpp/Strips/p01.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p02.pddl /home/matheus/mestrado/comp/tpp/Strips/p02.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p03.pddl /home/matheus/mestrado/comp/tpp/Strips/p03.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p04.pddl /home/matheus/mestrado/comp/tpp/Strips/p04.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p05.pddl /home/matheus/mestrado/comp/tpp/Strips/p05.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p06.pddl /home/matheus/mestrado/comp/tpp/Strips/p06.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p07.pddl /home/matheus/mestrado/comp/tpp/Strips/p07.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p08.pddl /home/matheus/mestrado/comp/tpp/Strips/p08.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p09.pddl /home/matheus/mestrado/comp/tpp/Strips/p09.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p10.pddl /home/matheus/mestrado/comp/tpp/Strips/p10.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p11.pddl /home/matheus/mestrado/comp/tpp/Strips/p11.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p12.pddl /home/matheus/mestrado/comp/tpp/Strips/p12.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p13.pddl /home/matheus/mestrado/comp/tpp/Strips/p13.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p14.pddl /home/matheus/mestrado/comp/tpp/Strips/p14.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p15.pddl /home/matheus/mestrado/comp/tpp/Strips/p15.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p16.pddl /home/matheus/mestrado/comp/tpp/Strips/p16.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p17.pddl /home/matheus/mestrado/comp/tpp/Strips/p17.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p18.pddl /home/matheus/mestrado/comp/tpp/Strips/p18.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p19.pddl /home/matheus/mestrado/comp/tpp/Strips/p19.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p20.pddl /home/matheus/mestrado/comp/tpp/Strips/p20.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p21.pddl /home/matheus/mestrado/comp/tpp/Strips/p21.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p22.pddl /home/matheus/mestrado/comp/tpp/Strips/p22.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p23.pddl /home/matheus/mestrado/comp/tpp/Strips/p23.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p24.pddl /home/matheus/mestrado/comp/tpp/Strips/p24.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p25.pddl /home/matheus/mestrado/comp/tpp/Strips/p25.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p26.pddl /home/matheus/mestrado/comp/tpp/Strips/p26.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p27.pddl /home/matheus/mestrado/comp/tpp/Strips/p27.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p28.pddl /home/matheus/mestrado/comp/tpp/Strips/p28.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p29.pddl /home/matheus/mestrado/comp/tpp/Strips/p29.pddl
timeout 1200 ./yahsp /home/matheus/mestrado/comp/tpp/Strips/domain_p30.pddl /home/matheus/mestrado/comp/tpp/Strips/p30.pddl
